export const tournamentConfig = {
  id: "world-leagues-2026",
  name: "Mundial de Ligas de Futbol",
  editionName: "Temporada 1",
  groupCount: 12,
  teamsPerGroup: 4,
  promotedPerGroup: 2,
  bestThirds: 8,
  squadSize: 26,
  rankingScale: { min: 1, max: 100 },
  tiebreakers: [
    "points",
    "goalDifference",
    "goalsFor",
    "headToHead",
    "leagueRanking",
    "draw"
  ],
  eligibilityRules: {
    cutoffDaysBeforeTournament: 90,
    contractMustRemainValidThroughYearEnd: true,
    maxPlayersPerClub: 4,
    minimumDistinctClubs: 8,
    loanedPlayersRepresentCurrentLeague: true,
    nationalityMatters: false
  }
};

export const leagues = [
  { id: "premier-league", name: "Premier League", region: "Inglaterra", level: 100, pot: 1 },
  { id: "laliga", name: "LaLiga", region: "Espana", level: 95, pot: 1 },
  { id: "serie-a", name: "Serie A", region: "Italia", level: 93, pot: 1 },
  { id: "bundesliga", name: "Bundesliga", region: "Alemania", level: 92, pot: 1 },
  { id: "ligue-1", name: "Ligue 1", region: "Francia", level: 89, pot: 1 },
  { id: "brasileirao", name: "Brasileirao Serie A", region: "Brasil", level: 86, pot: 1 },
  { id: "primeira-liga", name: "Primeira Liga", region: "Portugal", level: 83, pot: 1 },
  { id: "eredivisie", name: "Eredivisie", region: "Paises Bajos", level: 81, pot: 1 },
  { id: "liga-profesional-argentina", name: "Liga Profesional Argentina", region: "Argentina", level: 80, pot: 1 },
  { id: "saudi-pro-league", name: "Saudi Pro League", region: "Arabia Saudita", level: 78, pot: 1 },
  { id: "mls", name: "MLS", region: "Estados Unidos / Canada", level: 77, pot: 1 },
  { id: "liga-mx", name: "Liga MX", region: "Mexico", level: 76, pot: 1 },
  { id: "super-lig", name: "Super Lig", region: "Turquia", level: 75, pot: 2 },
  { id: "belgian-pro-league", name: "Belgian Pro League", region: "Belgica", level: 74, pot: 2 },
  { id: "russian-premier-league", name: "Russian Premier League", region: "Rusia", level: 73, pot: 2 },
  { id: "czech-first-league", name: "Czech First League", region: "Republica Checa", level: 72, pot: 2 },
  { id: "super-league-greece", name: "Super League Greece", region: "Grecia", level: 72, pot: 2 },
  { id: "danish-superliga", name: "Danish Superliga", region: "Dinamarca", level: 71, pot: 2 },
  { id: "scottish-premiership", name: "Scottish Premiership", region: "Escocia", level: 70, pot: 2 },
  { id: "austrian-bundesliga", name: "Austrian Bundesliga", region: "Austria", level: 70, pot: 2 },
  { id: "swiss-super-league", name: "Swiss Super League", region: "Suiza", level: 69, pot: 2 },
  { id: "serbian-superliga", name: "Serbian SuperLiga", region: "Serbia", level: 68, pot: 2 },
  { id: "croatian-hnl", name: "Croatian HNL", region: "Croacia", level: 68, pot: 2 },
  { id: "ukrainian-premier-league", name: "Ukrainian Premier League", region: "Ucrania", level: 67, pot: 2 },
  { id: "ekstraklasa", name: "Ekstraklasa", region: "Polonia", level: 66, pot: 3 },
  { id: "categoria-primera-a", name: "Categoria Primera A", region: "Colombia", level: 66, pot: 3 },
  { id: "primera-paraguay", name: "Primera Division", region: "Paraguay", level: 65, pot: 3 },
  { id: "ligapro-ecuador", name: "LigaPro", region: "Ecuador", level: 64, pot: 3 },
  { id: "egyptian-premier-league", name: "Egyptian Premier League", region: "Egipto", level: 64, pot: 3 },
  { id: "j1-league", name: "J1 League", region: "Japon", level: 63, pot: 3 },
  { id: "k-league-1", name: "K League 1", region: "Corea del Sur", level: 63, pot: 3 },
  { id: "uae-pro-league", name: "UAE Pro League", region: "Emiratos Arabes", level: 62, pot: 3 },
  { id: "botola-pro", name: "Botola Pro", region: "Marruecos", level: 62, pot: 3 },
  { id: "romanian-superliga", name: "Romanian SuperLiga", region: "Rumania", level: 61, pot: 3 },
  { id: "israeli-premier-league", name: "Israeli Premier League", region: "Israel", level: 61, pot: 3 },
  { id: "eliteserien", name: "Eliteserien", region: "Noruega", level: 60, pot: 3 },
  { id: "allsvenskan", name: "Allsvenskan", region: "Suecia", level: 60, pot: 4 },
  { id: "primera-chile", name: "Primera Division", region: "Chile", level: 59, pot: 4 },
  { id: "primera-uruguay", name: "Primera Division", region: "Uruguay", level: 59, pot: 4 },
  { id: "liga-1-peru", name: "Liga 1", region: "Peru", level: 58, pot: 4 },
  { id: "ligue-professionnelle-1-algeria", name: "Ligue Professionnelle 1", region: "Argelia", level: 58, pot: 4 },
  { id: "south-african-premiership", name: "South African Premiership", region: "Sudafrica", level: 57, pot: 4 },
  { id: "tunisian-ligue-professionnelle", name: "Tunisian Ligue Professionnelle", region: "Tunez", level: 57, pot: 4 },
  { id: "cypriot-first-division", name: "Cypriot First Division", region: "Chipre", level: 57, pot: 4 },
  { id: "a-league-men", name: "A-League Men", region: "Australia", level: 56, pot: 4 },
  { id: "qatar-stars-league", name: "Qatar Stars League", region: "Qatar", level: 56, pot: 4 },
  { id: "primera-costa-rica", name: "Primera Division", region: "Costa Rica", level: 55, pot: 4 },
  { id: "chinese-super-league", name: "Chinese Super League", region: "China", level: 55, pot: 4 }
];

export const leagueLogoCodes = {
  "premier-league": "PL",
  laliga: "LL",
  "serie-a": "SA",
  bundesliga: "BL",
  "ligue-1": "L1",
  brasileirao: "BR",
  "primeira-liga": "PT",
  eredivisie: "ER",
  "liga-profesional-argentina": "LPF",
  "saudi-pro-league": "SPL",
  mls: "MLS",
  "liga-mx": "MX",
  "super-lig": "SL",
  "belgian-pro-league": "BPL",
  "russian-premier-league": "RPL",
  "czech-first-league": "CZ",
  "super-league-greece": "GR",
  "danish-superliga": "DK",
  "scottish-premiership": "SP",
  "austrian-bundesliga": "AT",
  "swiss-super-league": "CH",
  "serbian-superliga": "RS",
  "croatian-hnl": "HNL",
  "ukrainian-premier-league": "UPL",
  ekstraklasa: "EKS",
  "categoria-primera-a": "COL",
  "primera-paraguay": "PY",
  "ligapro-ecuador": "EC",
  "egyptian-premier-league": "EG",
  "j1-league": "J1",
  "k-league-1": "K1",
  "uae-pro-league": "UAE",
  "botola-pro": "BOT",
  "romanian-superliga": "RO",
  "israeli-premier-league": "IL",
  eliteserien: "ELI",
  allsvenskan: "ALL",
  "primera-chile": "CL",
  "primera-uruguay": "UY",
  "liga-1-peru": "PE",
  "ligue-professionnelle-1-algeria": "DZ",
  "south-african-premiership": "PSL",
  "tunisian-ligue-professionnelle": "TN",
  "cypriot-first-division": "CY",
  "a-league-men": "AUS",
  "qatar-stars-league": "QSL",
  "primera-costa-rica": "CR",
  "chinese-super-league": "CSL"
};

export const leagueFlags = {
  "premier-league": [{ emoji: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", twemoji: "1f3f4-e0067-e0062-e0065-e006e-e0067-e007f" }],
  laliga: [{ emoji: "🇪🇸", twemoji: "1f1ea-1f1f8" }],
  "serie-a": [{ emoji: "🇮🇹", twemoji: "1f1ee-1f1f9" }],
  bundesliga: [{ emoji: "🇩🇪", twemoji: "1f1e9-1f1ea" }],
  "ligue-1": [{ emoji: "🇫🇷", twemoji: "1f1eb-1f1f7" }],
  brasileirao: [{ emoji: "🇧🇷", twemoji: "1f1e7-1f1f7" }],
  "primeira-liga": [{ emoji: "🇵🇹", twemoji: "1f1f5-1f1f9" }],
  eredivisie: [{ emoji: "🇳🇱", twemoji: "1f1f3-1f1f1" }],
  "liga-profesional-argentina": [{ emoji: "🇦🇷", twemoji: "1f1e6-1f1f7" }],
  "saudi-pro-league": [{ emoji: "🇸🇦", twemoji: "1f1f8-1f1e6" }],
  mls: [
    { emoji: "🇺🇸", twemoji: "1f1fa-1f1f8" },
    { emoji: "🇨🇦", twemoji: "1f1e8-1f1e6" }
  ],
  "liga-mx": [{ emoji: "🇲🇽", twemoji: "1f1f2-1f1fd" }],
  "super-lig": [{ emoji: "🇹🇷", twemoji: "1f1f9-1f1f7" }],
  "belgian-pro-league": [{ emoji: "🇧🇪", twemoji: "1f1e7-1f1ea" }],
  "russian-premier-league": [{ emoji: "🇷🇺", twemoji: "1f1f7-1f1fa" }],
  "czech-first-league": [{ emoji: "🇨🇿", twemoji: "1f1e8-1f1ff" }],
  "super-league-greece": [{ emoji: "🇬🇷", twemoji: "1f1ec-1f1f7" }],
  "danish-superliga": [{ emoji: "🇩🇰", twemoji: "1f1e9-1f1f0" }],
  "scottish-premiership": [{ emoji: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", twemoji: "1f3f4-e0067-e0062-e0073-e0063-e0074-e007f" }],
  "austrian-bundesliga": [{ emoji: "🇦🇹", twemoji: "1f1e6-1f1f9" }],
  "swiss-super-league": [{ emoji: "🇨🇭", twemoji: "1f1e8-1f1ed" }],
  "serbian-superliga": [{ emoji: "🇷🇸", twemoji: "1f1f7-1f1f8" }],
  "croatian-hnl": [{ emoji: "🇭🇷", twemoji: "1f1ed-1f1f7" }],
  "ukrainian-premier-league": [{ emoji: "🇺🇦", twemoji: "1f1fa-1f1e6" }],
  ekstraklasa: [{ emoji: "🇵🇱", twemoji: "1f1f5-1f1f1" }],
  "categoria-primera-a": [{ emoji: "🇨🇴", twemoji: "1f1e8-1f1f4" }],
  "primera-paraguay": [{ emoji: "🇵🇾", twemoji: "1f1f5-1f1fe" }],
  "ligapro-ecuador": [{ emoji: "🇪🇨", twemoji: "1f1ea-1f1e8" }],
  "egyptian-premier-league": [{ emoji: "🇪🇬", twemoji: "1f1ea-1f1ec" }],
  "j1-league": [{ emoji: "🇯🇵", twemoji: "1f1ef-1f1f5" }],
  "k-league-1": [{ emoji: "🇰🇷", twemoji: "1f1f0-1f1f7" }],
  "uae-pro-league": [{ emoji: "🇦🇪", twemoji: "1f1e6-1f1ea" }],
  "botola-pro": [{ emoji: "🇲🇦", twemoji: "1f1f2-1f1e6" }],
  "romanian-superliga": [{ emoji: "🇷🇴", twemoji: "1f1f7-1f1f4" }],
  "israeli-premier-league": [{ emoji: "🇮🇱", twemoji: "1f1ee-1f1f1" }],
  eliteserien: [{ emoji: "🇳🇴", twemoji: "1f1f3-1f1f4" }],
  allsvenskan: [{ emoji: "🇸🇪", twemoji: "1f1f8-1f1ea" }],
  "primera-chile": [{ emoji: "🇨🇱", twemoji: "1f1e8-1f1f1" }],
  "primera-uruguay": [{ emoji: "🇺🇾", twemoji: "1f1fa-1f1fe" }],
  "liga-1-peru": [{ emoji: "🇵🇪", twemoji: "1f1f5-1f1ea" }],
  "ligue-professionnelle-1-algeria": [{ emoji: "🇩🇿", twemoji: "1f1e9-1f1ff" }],
  "south-african-premiership": [{ emoji: "🇿🇦", twemoji: "1f1ff-1f1e6" }],
  "tunisian-ligue-professionnelle": [{ emoji: "🇹🇳", twemoji: "1f1f9-1f1f3" }],
  "cypriot-first-division": [{ emoji: "🇨🇾", twemoji: "1f1e8-1f1fe" }],
  "a-league-men": [{ emoji: "🇦🇺", twemoji: "1f1e6-1f1fa" }],
  "qatar-stars-league": [{ emoji: "🇶🇦", twemoji: "1f1f6-1f1e6" }],
  "primera-costa-rica": [{ emoji: "🇨🇷", twemoji: "1f1e8-1f1f7" }],
  "chinese-super-league": [{ emoji: "🇨🇳", twemoji: "1f1e8-1f1f3" }]
};

export const groups = [
  { id: "A", leagueIds: ["premier-league", "ukrainian-premier-league", "israeli-premier-league", "qatar-stars-league"] },
  { id: "B", leagueIds: ["laliga", "croatian-hnl", "ligapro-ecuador", "a-league-men"] },
  { id: "C", leagueIds: ["serie-a", "serbian-superliga", "j1-league", "liga-1-peru"] },
  { id: "D", leagueIds: ["bundesliga", "austrian-bundesliga", "botola-pro", "primera-chile"] },
  { id: "E", leagueIds: ["ligue-1", "swiss-super-league", "primera-paraguay", "chinese-super-league"] },
  { id: "F", leagueIds: ["brasileirao", "russian-premier-league", "eliteserien", "south-african-premiership"] },
  { id: "G", leagueIds: ["primeira-liga", "belgian-pro-league", "uae-pro-league", "primera-costa-rica"] },
  { id: "H", leagueIds: ["eredivisie", "czech-first-league", "k-league-1", "primera-uruguay"] },
  { id: "I", leagueIds: ["liga-profesional-argentina", "scottish-premiership", "egyptian-premier-league", "allsvenskan"] },
  { id: "J", leagueIds: ["saudi-pro-league", "super-lig", "romanian-superliga", "cypriot-first-division"] },
  { id: "K", leagueIds: ["mls", "danish-superliga", "categoria-primera-a", "ligue-professionnelle-1-algeria"] },
  { id: "L", leagueIds: ["liga-mx", "super-league-greece", "ekstraklasa", "tunisian-ligue-professionnelle"] }
];
