const starterSlots = [
  [1, "GK", "Arquero"],
  [2, "RB", "Lateral derecho"],
  [4, "CB", "Central"],
  [5, "CB", "Central"],
  [3, "LB", "Lateral izquierdo"],
  [6, "DM", "Mediocentro"],
  [8, "CM", "Interior"],
  [10, "AM", "Enganche"],
  [11, "RW", "Extremo derecho"],
  [9, "ST", "Delantero centro"],
  [7, "LW", "Extremo izquierdo"]
];

const benchSlots = [
  [12, "GK", "Arquero"],
  [13, "GK", "Arquero"],
  [14, "RB", "Lateral"],
  [15, "CB", "Central"],
  [16, "CB", "Central"],
  [17, "LB", "Lateral"],
  [18, "CM", "Interior"],
  [19, "CM", "Mediocampista"],
  [20, "AM", "Volante ofensivo"],
  [21, "AM", "Volante ofensivo"],
  [22, "ST", "Delantero"],
  [23, "ST", "Delantero"],
  [24, "ST", "Delantero"],
  [25, "W", "Extremo"],
  [26, "W", "Extremo"]
];

const squadSlots = [...starterSlots, ...benchSlots];

const countries = {
  AO: ["Angola", "🇦🇴"],
  DZ: ["Argelia", "🇩🇿"],
  AR: ["Argentina", "🇦🇷"],
  AL: ["Albania", "🇦🇱"],
  AM: ["Armenia", "🇦🇲"],
  AU: ["Australia", "🇦🇺"],
  AT: ["Austria", "🇦🇹"],
  BE: ["Belgica", "🇧🇪"],
  BA: ["Bosnia y Herzegovina", "🇧🇦"],
  BF: ["Burkina Faso", "🇧🇫"],
  BR: ["Brasil", "🇧🇷"],
  CA: ["Canada", "🇨🇦"],
  CM: ["Camerun", "🇨🇲"],
  CL: ["Chile", "🇨🇱"],
  CN: ["China", "🇨🇳"],
  CO: ["Colombia", "🇨🇴"],
  CR: ["Costa Rica", "🇨🇷"],
  CU: ["Cuba", "🇨🇺"],
  CW: ["Curazao", "🇨🇼"],
  CV: ["Cabo Verde", "🇨🇻"],
  CI: ["Costa de Marfil", "🇨🇮"],
  CD: ["RD Congo", "🇨🇩"],
  HR: ["Croacia", "🇭🇷"],
  CY: ["Chipre", "🇨🇾"],
  CZ: ["Republica Checa", "🇨🇿"],
  DK: ["Dinamarca", "🇩🇰"],
  EC: ["Ecuador", "🇪🇨"],
  EG: ["Egipto", "🇪🇬"],
  ENG: ["Inglaterra", "🏴󠁧󠁢󠁥󠁮󠁧󠁿"],
  FR: ["Francia", "🇫🇷"],
  FI: ["Finlandia", "🇫🇮"],
  GA: ["Gabon", "🇬🇦"],
  DE: ["Alemania", "🇩🇪"],
  GE: ["Georgia", "🇬🇪"],
  GH: ["Ghana", "🇬🇭"],
  GM: ["Gambia", "🇬🇲"],
  GN: ["Guinea", "🇬🇳"],
  GW: ["Guinea-Bisau", "🇬🇼"],
  GR: ["Grecia", "🇬🇷"],
  HN: ["Honduras", "🇭🇳"],
  HT: ["Haiti", "🇭🇹"],
  IE: ["Irlanda", "🇮🇪"],
  IL: ["Israel", "🇮🇱"],
  IR: ["Iran", "🇮🇷"],
  IT: ["Italia", "🇮🇹"],
  JP: ["Japon", "🇯🇵"],
  KE: ["Kenia", "🇰🇪"],
  KR: ["Corea del Sur", "🇰🇷"],
  LR: ["Liberia", "🇱🇷"],
  MA: ["Marruecos", "🇲🇦"],
  MK: ["Macedonia del Norte", "🇲🇰"],
  ML: ["Mali", "🇲🇱"],
  MX: ["Mexico", "🇲🇽"],
  NL: ["Paises Bajos", "🇳🇱"],
  NA: ["Namibia", "🇳🇦"],
  NG: ["Nigeria", "🇳🇬"],
  NO: ["Noruega", "🇳🇴"],
  PY: ["Paraguay", "🇵🇾"],
  PE: ["Peru", "🇵🇪"],
  PL: ["Polonia", "🇵🇱"],
  PT: ["Portugal", "🇵🇹"],
  QA: ["Qatar", "🇶🇦"],
  RO: ["Rumania", "🇷🇴"],
  RU: ["Rusia", "🇷🇺"],
  SA: ["Arabia Saudita", "🇸🇦"],
  SN: ["Senegal", "🇸🇳"],
  RS: ["Serbia", "🇷🇸"],
  SI: ["Eslovenia", "🇸🇮"],
  SK: ["Eslovaquia", "🇸🇰"],
  SCT: ["Escocia", "🏴󠁧󠁢󠁳󠁣󠁴󠁿"],
  ZA: ["Sudafrica", "🇿🇦"],
  ES: ["Espana", "🇪🇸"],
  SE: ["Suecia", "🇸🇪"],
  CH: ["Suiza", "🇨🇭"],
  TN: ["Tunez", "🇹🇳"],
  TG: ["Togo", "🇹🇬"],
  TR: ["Turquia", "🇹🇷"],
  TT: ["Trinidad y Tobago", "🇹🇹"],
  UA: ["Ucrania", "🇺🇦"],
  AE: ["Emiratos Arabes", "🇦🇪"],
  US: ["Estados Unidos", "🇺🇸"],
  UY: ["Uruguay", "🇺🇾"],
  WAL: ["Gales", "🏴󠁧󠁢󠁷󠁬󠁳󠁿"]
};

export const realSquads = {
  "premier-league": squad("Premier League", "pl", 5, [
    ["David Raya", "Arsenal", 88, "ES"],
    ["Reece James", "Chelsea", 84, "ENG"],
    ["Virgil van Dijk", "Liverpool", 90, "NL"],
    ["William Saliba", "Arsenal", 87, "FR"],
    ["Marc Cucurella", "Chelsea", 83, "ES"],
    ["Rodri", "Manchester City", 90, "ES"],
    ["Declan Rice", "Arsenal", 87, "ENG"],
    ["Florian Wirtz", "Liverpool", 88, "DE"],
    ["Mohamed Salah", "Liverpool", 91, "EG"],
    ["Erling Haaland", "Manchester City", 90, "NO"],
    ["Bukayo Saka", "Arsenal", 87, "ENG"],
    ["Alisson", "Liverpool", 89, "BR"],
    ["Gianluigi Donnarumma", "Manchester City", 88, "IT"],
    ["Gabriel Magalhaes", "Arsenal", 86, "BR"],
    ["Ibrahima Konate", "Liverpool", 86, "FR"],
    ["Ruben Dias", "Manchester City", 86, "PT"],
    ["Moises Caicedo", "Chelsea", 85, "EC"],
    ["Alexis Mac Allister", "Liverpool", 87, "AR"],
    ["Ryan Gravenberch", "Liverpool", 85, "NL"],
    ["Cole Palmer", "Chelsea", 87, "ENG"],
    ["Martin Odegaard", "Arsenal", 87, "NO"],
    ["Alexander Isak", "Liverpool", 87, "SE"],
    ["Viktor Gyokeres", "Arsenal", 86, "SE"],
    ["Ollie Watkins", "Aston Villa", 85, "ENG"],
    ["Joao Pedro", "Chelsea", 84, "BR"],
    ["Igor Thiago", "Brentford", 83, "BR"]
  ]),
  laliga: squad("LaLiga", "ll", 7, [
    ["Thibaut Courtois", "Real Madrid", 90, "BE"],
    ["Dani Carvajal", "Real Madrid", 85, "ES"],
    ["Eder Militao", "Real Madrid", 86, "BR"],
    ["Ronald Araujo", "Barcelona", 85, "UY"],
    ["Alejandro Balde", "Barcelona", 82, "ES"],
    ["Federico Valverde", "Real Madrid", 88, "UY"],
    ["Pedri", "Barcelona", 87, "ES"],
    ["Jude Bellingham", "Real Madrid", 90, "ENG"],
    ["Lamine Yamal", "Barcelona", 89, "ES"],
    ["Kylian Mbappe", "Real Madrid", 91, "FR"],
    ["Vinicius Junior", "Real Madrid", 90, "BR"],
    ["Jan Oblak", "Atletico Madrid", 88, "SI"],
    ["Unai Simon", "Athletic Club", 84, "ES"],
    ["Jules Kounde", "Barcelona", 85, "FR"],
    ["Pau Cubarsi", "Barcelona", 83, "ES"],
    ["Antonio Rudiger", "Real Madrid", 86, "DE"],
    ["Ferland Mendy", "Real Madrid", 82, "FR"],
    ["Aurelien Tchouameni", "Real Madrid", 85, "FR"],
    ["Frenkie de Jong", "Barcelona", 86, "NL"],
    ["Gavi", "Barcelona", 84, "ES"],
    ["Isco", "Real Betis", 84, "ES"],
    ["Nico Williams", "Athletic Club", 85, "ES"],
    ["Robert Lewandowski", "Barcelona", 88, "PL"],
    ["Antoine Griezmann", "Atletico Madrid", 88, "FR"],
    ["Raphinha", "Barcelona", 87, "BR"],
    ["Rodrygo", "Real Madrid", 86, "BR"]
  ]),
  "serie-a": squad("Serie A", "sa", 8, [
    ["Yann Sommer", "Inter", 86, "CH"],
    ["Giovanni Di Lorenzo", "Napoli", 84, "IT"],
    ["Alessandro Bastoni", "Inter", 87, "IT"],
    ["Bremer", "Juventus", 86, "BR"],
    ["Theo Hernandez", "Milan", 86, "FR"],
    ["Hakan Calhanoglu", "Inter", 86, "TR"],
    ["Nicolo Barella", "Inter", 87, "IT"],
    ["Paulo Dybala", "Roma", 86, "AR"],
    ["Christian Pulisic", "Milan", 84, "US"],
    ["Lautaro Martinez", "Inter", 89, "AR"],
    ["Rafael Leao", "Milan", 86, "PT"],
    ["Mike Maignan", "Milan", 87, "FR"],
    ["Mile Svilar", "Roma", 82, "RS"],
    ["Denzel Dumfries", "Inter", 82, "NL"],
    ["Alessandro Buongiorno", "Napoli", 84, "IT"],
    ["Francesco Acerbi", "Inter", 83, "IT"],
    ["Federico Dimarco", "Inter", 85, "IT"],
    ["Manuel Locatelli", "Juventus", 83, "IT"],
    ["Scott McTominay", "Napoli", 83, "SCT"],
    ["Teun Koopmeiners", "Juventus", 83, "NL"],
    ["Kenan Yildiz", "Juventus", 82, "TR"],
    ["Kevin De Bruyne", "Napoli", 88, "BE"],
    ["Marcus Thuram", "Inter", 85, "FR"],
    ["Dusan Vlahovic", "Juventus", 84, "RS"],
    ["Moise Kean", "Fiorentina", 82, "IT"],
    ["Santiago Castro", "Bologna", 80, "AR"]
  ]),
  bundesliga: squad("Bundesliga", "bl", 10, [
    ["Manuel Neuer", "Bayern Munich", 86, "DE"],
    ["Konrad Laimer", "Bayern Munich", 82, "AT"],
    ["Jonathan Tah", "Bayern Munich", 85, "DE"],
    ["Nico Schlotterbeck", "Borussia Dortmund", 84, "DE"],
    ["Alphonso Davies", "Bayern Munich", 84, "CA"],
    ["Joshua Kimmich", "Bayern Munich", 87, "DE"],
    ["Aleksandar Pavlovic", "Bayern Munich", 82, "DE"],
    ["Jamal Musiala", "Bayern Munich", 89, "DE"],
    ["Michael Olise", "Bayern Munich", 86, "FR"],
    ["Harry Kane", "Bayern Munich", 90, "ENG"],
    ["Serhou Guirassy", "Borussia Dortmund", 85, "GN"],
    ["Gregor Kobel", "Borussia Dortmund", 86, "CH"],
    ["Oliver Baumann", "Hoffenheim", 83, "DE"],
    ["David Raum", "RB Leipzig", 82, "DE"],
    ["Dayot Upamecano", "Bayern Munich", 84, "FR"],
    ["Waldemar Anton", "Borussia Dortmund", 82, "DE"],
    ["Maximilian Mittelstadt", "Stuttgart", 81, "DE"],
    ["Robert Andrich", "Bayer Leverkusen", 82, "DE"],
    ["Angelo Stiller", "Stuttgart", 82, "DE"],
    ["Julian Brandt", "Borussia Dortmund", 83, "DE"],
    ["Serge Gnabry", "Bayern Munich", 83, "DE"],
    ["Florian Grillitsch", "Hoffenheim", 80, "AT"],
    ["Victor Boniface", "Bayer Leverkusen", 83, "NG"],
    ["Benjamin Sesko", "RB Leipzig", 83, "SI"],
    ["Patrik Schick", "Bayer Leverkusen", 83, "CZ"],
    ["Jamie Gittens", "Borussia Dortmund", 82, "ENG"]
  ]),
  "ligue-1": squad("Ligue 1", "l1", 8, [
    ["Lucas Chevalier", "Paris Saint-Germain", 84, "FR"],
    ["Achraf Hakimi", "Paris Saint-Germain", 85, "MA"],
    ["Marquinhos", "Paris Saint-Germain", 86, "BR"],
    ["Willian Pacho", "Paris Saint-Germain", 84, "EC"],
    ["Nuno Mendes", "Paris Saint-Germain", 86, "PT"],
    ["Vitinha", "Paris Saint-Germain", 87, "PT"],
    ["Joao Neves", "Paris Saint-Germain", 84, "PT"],
    ["Desire Doue", "Paris Saint-Germain", 84, "FR"],
    ["Ousmane Dembele", "Paris Saint-Germain", 89, "FR"],
    ["Jonathan David", "Lille", 85, "CA"],
    ["Khvicha Kvaratskhelia", "Paris Saint-Germain", 88, "GE"],
    ["Matvey Safonov", "Paris Saint-Germain", 80, "RU"],
    ["Brice Samba", "Rennes", 83, "FR"],
    ["Jonathan Clauss", "Nice", 81, "FR"],
    ["Duje Caleta-Car", "Lyon", 79, "HR"],
    ["Moussa Niakhate", "Lyon", 80, "SN"],
    ["Caio Henrique", "Monaco", 81, "BR"],
    ["Denis Zakaria", "Monaco", 82, "CH"],
    ["Tanguy Ndombele", "Nice", 80, "FR"],
    ["Aleksandr Golovin", "Monaco", 83, "RU"],
    ["Rayan Cherki", "Lyon", 83, "FR"],
    ["Bradley Barcola", "Paris Saint-Germain", 85, "FR"],
    ["Folarin Balogun", "Monaco", 81, "US"],
    ["Elye Wahi", "Marseille", 80, "FR"],
    ["Mason Greenwood", "Marseille", 83, "ENG"],
    ["Georges Mikautadze", "Lyon", 81, "GE"]
  ]),
  brasileirao: squad("Brasileirao Serie A", "br", 8, [
    ["Weverton", "Palmeiras", 82, "BR"],
    ["Gustavo Gomez", "Palmeiras", 82, "PY"],
    ["Fabricio Bruno", "Cruzeiro", 79, "BR"],
    ["Leo Ortiz", "Flamengo", 80, "BR"],
    ["Guilherme Arana", "Atletico Mineiro", 80, "BR"],
    ["Gerson", "Flamengo", 82, "BR"],
    ["Andreas Pereira", "Palmeiras", 81, "BR"],
    ["Arrascaeta", "Flamengo", 84, "UY"],
    ["Estevao", "Palmeiras", 81, "BR"],
    ["Pedro", "Flamengo", 83, "BR"],
    ["Memphis Depay", "Corinthians", 83, "NL"],
    ["Rossi", "Flamengo", 80, "AR"],
    ["Bento", "Athletico Paranaense", 80, "BR"],
    ["Marcos Rocha", "Palmeiras", 77, "BR"],
    ["Murilo", "Palmeiras", 79, "BR"],
    ["Bastos", "Botafogo", 78, "AO"],
    ["Alex Sandro", "Flamengo", 80, "BR"],
    ["Raphael Veiga", "Palmeiras", 82, "BR"],
    ["Matheus Pereira", "Cruzeiro", 81, "BR"],
    ["Philippe Coutinho", "Vasco da Gama", 80, "BR"],
    ["Alan Patrick", "Internacional", 81, "BR"],
    ["Hulk", "Atletico Mineiro", 82, "BR"],
    ["Yuri Alberto", "Corinthians", 79, "BR"],
    ["Tiquinho Soares", "Santos", 78, "BR"],
    ["Luiz Henrique", "Botafogo", 82, "BR"],
    ["Bruno Henrique", "Flamengo", 80, "BR"]
  ]),
  "primeira-liga": squad("Primeira Liga", "pt", 9, [
    ["Diogo Costa", "Porto", 85, "PT"],
    ["Alexander Bah", "Benfica", 80, "DK"],
    ["Antonio Silva", "Benfica", 82, "PT"],
    ["Goncalo Inacio", "Sporting CP", 83, "PT"],
    ["Nuno Santos", "Sporting CP", 81, "PT"],
    ["Morten Hjulmand", "Sporting CP", 82, "DK"],
    ["Orkun Kokcu", "Benfica", 82, "TR"],
    ["Pedro Goncalves", "Sporting CP", 84, "PT"],
    ["Francisco Trincao", "Sporting CP", 82, "PT"],
    ["Viktor Gyokeres", "Sporting CP", 87, "SE"],
    ["Kerem Akturkoglu", "Benfica", 82, "TR"],
    ["Anatoliy Trubin", "Benfica", 82, "UA"],
    ["Rui Silva", "Sporting CP", 80, "PT"],
    ["Joao Mario", "Porto", 79, "PT"],
    ["Otamendi", "Benfica", 82, "AR"],
    ["Ousmane Diomande", "Sporting CP", 82, "CI"],
    ["Alvaro Carreras", "Benfica", 80, "ES"],
    ["Alan Varela", "Porto", 81, "AR"],
    ["Florentino Luis", "Benfica", 80, "PT"],
    ["Franco Israel", "Sporting CP", 78, "UY"],
    ["Fabio Vieira", "Porto", 81, "PT"],
    ["Angel Di Maria", "Benfica", 84, "AR"],
    ["Vangelis Pavlidis", "Benfica", 82, "GR"],
    ["Samu Aghehowa", "Porto", 82, "ES"],
    ["Galeno", "Porto", 81, "BR"],
    ["Bruma", "Benfica", 80, "PT"]
  ]),
  eredivisie: squad("Eredivisie", "er", 8, [
    ["Walter Benitez", "PSV", 81, "AR"],
    ["Devyne Rensch", "Ajax", 78, "NL"],
    ["Jorrel Hato", "Ajax", 81, "NL"],
    ["David Hancko", "Feyenoord", 82, "SK"],
    ["Quilindschy Hartman", "Feyenoord", 79, "NL"],
    ["Jerdy Schouten", "PSV", 82, "NL"],
    ["Quinten Timber", "Feyenoord", 81, "NL"],
    ["Sem Steijn", "Feyenoord", 82, "NL"],
    ["Johan Bakayoko", "PSV", 82, "BE"],
    ["Luuk de Jong", "PSV", 83, "NL"],
    ["Noa Lang", "PSV", 81, "NL"],
    ["Remko Pasveer", "Ajax", 77, "NL"],
    ["Justin Bijlow", "Feyenoord", 79, "NL"],
    ["Jordan Teze", "PSV", 78, "NL"],
    ["Olivier Boscagli", "PSV", 80, "FR"],
    ["Josip Sutalo", "Ajax", 79, "HR"],
    ["Sergino Dest", "PSV", 79, "US"],
    ["Joey Veerman", "PSV", 82, "NL"],
    ["Kenneth Taylor", "Ajax", 80, "NL"],
    ["Steven Berghuis", "Ajax", 80, "NL"],
    ["Malik Tillman", "PSV", 82, "US"],
    ["Hirving Lozano", "PSV", 80, "MX"],
    ["Brian Brobbey", "Ajax", 81, "NL"],
    ["Santiago Gimenez", "Feyenoord", 82, "MX"],
    ["Igor Paixao", "Feyenoord", 81, "BR"],
    ["Ivan Perisic", "PSV", 81, "HR"]
  ]),
  "liga-profesional-argentina": squad("Liga Profesional Argentina", "lpf", 8, [
    ["Jorge Broun", "Rosario Central", 79, "AR"],
    ["Gonzalo Montiel", "River Plate", 80, "AR"],
    ["Paulo Diaz", "River Plate", 80, "CL"],
    ["Facundo Mallo", "Rosario Central", 78, "UY"],
    ["Marcos Acuna", "River Plate", 81, "AR"],
    ["Leandro Paredes", "Boca Juniors", 83, "AR"],
    ["Enzo Perez", "Estudiantes (LP)", 78, "AR"],
    ["Juan Fernando Quintero", "River Plate", 80, "CO"],
    ["Angel Di Maria", "Rosario Central", 84, "AR"],
    ["Miguel Merentiel", "Boca Juniors", 79, "UY"],
    ["Sebastian Villa", "Independiente Rivadavia", 78, "CO"],
    ["Fernando Muslera", "Estudiantes (LP)", 80, "UY"],
    ["Gabriel Arias", "Racing", 78, "CL"],
    ["Luis Advincula", "Boca Juniors", 78, "PE"],
    ["German Pezzella", "River Plate", 79, "AR"],
    ["Santiago Sosa", "Racing", 78, "AR"],
    ["Gabriel Rojas", "Racing", 77, "AR"],
    ["Ever Banega", "Newell's Old Boys", 78, "AR"],
    ["Cristian Medina", "Estudiantes (LP)", 78, "AR"],
    ["Ignacio Malcorra", "Rosario Central", 78, "AR"],
    ["Alan Lescano", "Argentinos Juniors", 77, "AR"],
    ["Tomas Molina", "Argentinos Juniors", 78, "AR"],
    ["Ronaldo Martinez", "Platense", 78, "PY"],
    ["Adrian Martinez", "Racing", 79, "AR"],
    ["Alejo Veliz", "Rosario Central", 77, "AR"],
    ["Edwuin Cetre", "Estudiantes (LP)", 77, "CO"]
  ]),
  "saudi-pro-league": squad("Saudi Pro League", "spl", 9, [
    ["Yassine Bounou", "Al Hilal", 84, "MA"],
    ["Joao Cancelo", "Al Hilal", 85, "PT"],
    ["Kalidou Koulibaly", "Al Hilal", 84, "SN"],
    ["Aymeric Laporte", "Al Nassr", 84, "ES"],
    ["Renan Lodi", "Al Hilal", 81, "BR"],
    ["N'Golo Kante", "Al Ittihad", 86, "FR"],
    ["Ruben Neves", "Al Hilal", 84, "PT"],
    ["Sergej Milinkovic-Savic", "Al Hilal", 85, "RS"],
    ["Riyad Mahrez", "Al Ahli", 85, "DZ"],
    ["Cristiano Ronaldo", "Al Nassr", 88, "PT"],
    ["Sadio Mane", "Al Nassr", 84, "SN"],
    ["Edouard Mendy", "Al Ahli", 82, "SN"],
    ["Predrag Rajkovic", "Al Ittihad", 80, "RS"],
    ["Saud Abdulhamid", "Al Hilal", 78, "SA"],
    ["Roger Ibanez", "Al Ahli", 80, "BR"],
    ["Merih Demiral", "Al Ahli", 80, "TR"],
    ["Alex Telles", "Al Nassr", 80, "BR"],
    ["Fabinho", "Al Ittihad", 84, "BR"],
    ["Marcelo Brozovic", "Al Nassr", 84, "HR"],
    ["Otavio", "Al Nassr", 82, "PT"],
    ["Roberto Firmino", "Al Ahli", 82, "BR"],
    ["Malcom", "Al Hilal", 83, "BR"],
    ["Karim Benzema", "Al Ittihad", 86, "FR"],
    ["Aleksandar Mitrovic", "Al Hilal", 84, "RS"],
    ["Ivan Toney", "Al Ahli", 83, "ENG"],
    ["Allan Saint-Maximin", "Al Ahli", 81, "FR"]
  ]),
  mls: squad("MLS", "mls", 8, [
    ["Roman Burki", "St. Louis City", 80, "CH"],
    ["DeAndre Yedlin", "FC Cincinnati", 73, "US"],
    ["Walker Zimmerman", "Nashville SC", 76, "US"],
    ["Miles Robinson", "FC Cincinnati", 75, "US"],
    ["Jordi Alba", "Inter Miami", 82, "ES"],
    ["Sergio Busquets", "Inter Miami", 83, "ES"],
    ["Hector Herrera", "Houston Dynamo", 78, "MX"],
    ["Luciano Acosta", "FC Dallas", 82, "AR"],
    ["Lionel Messi", "Inter Miami", 90, "AR"],
    ["Luis Suarez", "Inter Miami", 84, "UY"],
    ["Denis Bouanga", "Los Angeles FC", 82, "GA"],
    ["Brad Stuver", "Austin FC", 75, "US"],
    ["Hugo Lloris", "Los Angeles FC", 79, "FR"],
    ["Brooks Lennon", "Atlanta United", 73, "US"],
    ["Yeimar Gomez", "Seattle Sounders", 75, "CO"],
    ["Jakob Glesnes", "Philadelphia Union", 74, "NO"],
    ["Kai Wagner", "Philadelphia Union", 75, "DE"],
    ["Carles Gil", "New England Revolution", 80, "ES"],
    ["Evander", "FC Cincinnati", 81, "BR"],
    ["Riqui Puig", "LA Galaxy", 79, "ES"],
    ["Thiago Almada", "Atlanta United", 80, "AR"],
    ["Cucho Hernandez", "Columbus Crew", 82, "CO"],
    ["Christian Benteke", "D.C. United", 80, "BE"],
    ["Hany Mukhtar", "Nashville SC", 80, "DE"],
    ["Facundo Torres", "Orlando City", 78, "UY"],
    ["Diego Rossi", "Columbus Crew", 78, "UY"]
  ]),
  "liga-mx": squad("Liga MX", "mx", 8, [
    ["Luis Malagon", "America", 78, "MX"],
    ["Kevin Alvarez", "America", 75, "MX"],
    ["Igor Lichnovsky", "America", 76, "CL"],
    ["Jesus Orozco Chiquete", "Cruz Azul", 77, "MX"],
    ["Gerardo Arteaga", "Monterrey", 78, "MX"],
    ["Luis Romo", "Cruz Azul", 77, "MX"],
    ["Erick Sanchez", "America", 78, "MX"],
    ["Sergio Canales", "Monterrey", 82, "ES"],
    ["Juan Brunetta", "Tigres", 80, "AR"],
    ["Henry Martin", "America", 79, "MX"],
    ["Alexis Vega", "Toluca", 78, "MX"],
    ["Nahuel Guzman", "Tigres", 78, "AR"],
    ["Esteban Andrada", "Monterrey", 78, "AR"],
    ["Jorge Sanchez", "Cruz Azul", 76, "MX"],
    ["Victor Guzman", "Monterrey", 76, "MX"],
    ["Sebastian Caceres", "America", 77, "UY"],
    ["Jesus Angulo", "Tigres", 76, "MX"],
    ["Guido Pizarro", "Tigres", 77, "AR"],
    ["Alvaro Fidalgo", "America", 79, "ES"],
    ["Marcel Ruiz", "Toluca", 78, "MX"],
    ["Sebastian Cordova", "Tigres", 77, "MX"],
    ["Uriel Antuna", "Tigres", 77, "MX"],
    ["Andre-Pierre Gignac", "Tigres", 80, "FR"],
    ["German Berterame", "Monterrey", 78, "AR"],
    ["Paulinho", "Toluca", 79, "BR"],
    ["Roberto Alvarado", "Chivas", 78, "MX"]
  ]),
  "super-lig": squad("Super Lig", "tr", 9, [
    ["Dominik Livakovic", "Fenerbahce", 82, "HR"],
    ["Bright Osayi-Samuel", "Fenerbahce", 78, "NG"],
    ["Davinson Sanchez", "Galatasaray", 82, "CO"],
    ["Abdulkerim Bardakci", "Galatasaray", 79, "TR"],
    ["Ferdi Kadioglu", "Fenerbahce", 81, "TR"],
    ["Fred", "Fenerbahce", 81, "BR"],
    ["Lucas Torreira", "Galatasaray", 82, "UY"],
    ["Hakim Ziyech", "Galatasaray", 82, "MA"],
    ["Dusan Tadic", "Fenerbahce", 83, "RS"],
    ["Victor Osimhen", "Galatasaray", 88, "NG"],
    ["Mauro Icardi", "Galatasaray", 84, "AR"],
    ["Fernando Muslera", "Galatasaray", 81, "UY"],
    ["Ugurcan Cakir", "Trabzonspor", 80, "TR"],
    ["Mert Muldur", "Fenerbahce", 77, "TR"],
    ["Victor Nelsson", "Galatasaray", 80, "DK"],
    ["Caglar Soyuncu", "Fenerbahce", 79, "TR"],
    ["Arthur Masuaku", "Besiktas", 78, "CD"],
    ["Sofyan Amrabat", "Fenerbahce", 81, "MA"],
    ["Gedson Fernandes", "Besiktas", 80, "PT"],
    ["Dries Mertens", "Galatasaray", 82, "BE"],
    ["Rafa Silva", "Besiktas", 82, "PT"],
    ["Edin Dzeko", "Fenerbahce", 83, "BA"],
    ["Ciro Immobile", "Besiktas", 82, "IT"],
    ["Michy Batshuayi", "Galatasaray", 80, "BE"],
    ["Allan Saint-Maximin", "Fenerbahce", 81, "FR"],
    ["Kerem Akturkoglu", "Galatasaray", 80, "TR"]
  ]),
  "belgian-pro-league": squad("Belgian Pro League", "be", 8, [
    ["Simon Mignolet", "Club Brugge", 80, "BE"],
    ["Clinton Mata", "Club Brugge", 76, "AO"],
    ["Jan Vertonghen", "Anderlecht", 78, "BE"],
    ["Brandon Mechele", "Club Brugge", 77, "BE"],
    ["Maxim De Cuyper", "Club Brugge", 78, "BE"],
    ["Hans Vanaken", "Club Brugge", 80, "BE"],
    ["Raphael Onyedika", "Club Brugge", 78, "NG"],
    ["Mario Stroeykens", "Anderlecht", 76, "BE"],
    ["Andreas Skov Olsen", "Club Brugge", 79, "DK"],
    ["Kasper Dolberg", "Anderlecht", 79, "DK"],
    ["Tolu Arokodare", "Genk", 78, "NG"],
    ["Koen Casteels", "Anderlecht", 80, "BE"],
    ["Maarten Vandevoordt", "Genk", 77, "BE"],
    ["Killian Sardella", "Anderlecht", 75, "BE"],
    ["Zeno Debast", "Anderlecht", 77, "BE"],
    ["Toby Alderweireld", "Antwerp", 78, "BE"],
    ["Bjorn Meijer", "Club Brugge", 76, "NL"],
    ["Bryan Heynen", "Genk", 77, "BE"],
    ["Cameron Puertas", "Union SG", 78, "ES"],
    ["Charles Vanhoutte", "Union SG", 76, "BE"],
    ["Gustaf Nilsson", "Union SG", 77, "SE"],
    ["Noah Sadiki", "Union SG", 75, "BE"],
    ["Kevin Denkey", "Cercle Brugge", 78, "TG"],
    ["Vincent Janssen", "Antwerp", 77, "NL"],
    ["Philip Zinckernagel", "Club Brugge", 77, "DK"],
    ["Anders Dreyer", "Anderlecht", 78, "DK"]
  ]),
  "russian-premier-league": squad("Russian Premier League", "ru", 8, [
    ["Matvey Safonov", "Krasnodar", 81, "RU"],
    ["Vyacheslav Karavaev", "Zenit", 76, "RU"],
    ["Nino", "Zenit", 78, "BR"],
    ["Strahinja Erakovic", "Zenit", 77, "RS"],
    ["Douglas Santos", "Zenit", 80, "BR"],
    ["Wendel", "Zenit", 80, "BR"],
    ["Wilmar Barrios", "Zenit", 80, "CO"],
    ["Claudinho", "Zenit", 81, "BR"],
    ["Malcom", "Zenit", 82, "BR"],
    ["Mateo Cassierra", "Zenit", 80, "CO"],
    ["Jhon Cordoba", "Krasnodar", 80, "CO"],
    ["Stanislav Agkatsev", "Krasnodar", 76, "RU"],
    ["Igor Akinfeev", "CSKA Moscow", 78, "RU"],
    ["Mario Fernandes", "Zenit", 76, "RU"],
    ["Georgiy Dzhikiya", "Spartak Moscow", 77, "RU"],
    ["Willyan Rocha", "CSKA Moscow", 76, "BR"],
    ["Daniil Khlusevich", "Spartak Moscow", 75, "RU"],
    ["Eduard Spertsyan", "Krasnodar", 80, "AM"],
    ["Danil Glebov", "Rostov", 76, "RU"],
    ["Daler Kuzyaev", "Zenit", 78, "RU"],
    ["Quincy Promes", "Spartak Moscow", 79, "NL"],
    ["Aleksandr Sobolev", "Zenit", 78, "RU"],
    ["Fedor Chalov", "CSKA Moscow", 77, "RU"],
    ["Konstantin Tyukavin", "Dynamo Moscow", 79, "RU"],
    ["Maksim Glushenkov", "Zenit", 79, "RU"],
    ["Manfred Ugalde", "Spartak Moscow", 77, "CR"]
  ]),
  "czech-first-league": squad("Czech First League", "cz", 8, [
    ["Jindrich Stanek", "Slavia Prague", 77, "CZ"],
    ["Tomas Holes", "Slavia Prague", 76, "CZ"],
    ["Ladislav Krejci", "Sparta Prague", 78, "CZ"],
    ["David Zima", "Slavia Prague", 76, "CZ"],
    ["Jaroslav Zeleny", "Sparta Prague", 75, "CZ"],
    ["Lukas Provod", "Slavia Prague", 77, "CZ"],
    ["Qazim Laci", "Sparta Prague", 75, "AL"],
    ["Veljko Birmancevic", "Sparta Prague", 77, "RS"],
    ["Lukas Haraslin", "Sparta Prague", 78, "SK"],
    ["Jan Kuchta", "Sparta Prague", 77, "CZ"],
    ["Mojmir Chytil", "Slavia Prague", 76, "CZ"],
    ["Peter Vindahl", "Sparta Prague", 75, "DK"],
    ["Ales Mandous", "Slavia Prague", 74, "CZ"],
    ["David Doudera", "Slavia Prague", 75, "CZ"],
    ["Asger Sorensen", "Sparta Prague", 75, "DK"],
    ["Igoh Ogbu", "Slavia Prague", 76, "NG"],
    ["Matej Rynes", "Sparta Prague", 74, "CZ"],
    ["Oscar Dorley", "Slavia Prague", 76, "LR"],
    ["Christos Zafeiris", "Slavia Prague", 76, "GR"],
    ["Kaan Kairinen", "Sparta Prague", 75, "FI"],
    ["Adam Karabec", "Sparta Prague", 74, "CZ"],
    ["Vaclav Cerny", "Sparta Prague", 76, "CZ"],
    ["Tomas Chory", "Slavia Prague", 76, "CZ"],
    ["Daniel Vasulin", "Viktoria Plzen", 74, "CZ"],
    ["Pavel Sulc", "Viktoria Plzen", 77, "CZ"],
    ["Cadu", "Viktoria Plzen", 74, "BR"]
  ]),
  "super-league-greece": squad("Super League Greece", "gr", 8, [
    ["Dominik Kotarski", "PAOK", 78, "HR"],
    ["Rodinei", "Olympiacos", 79, "BR"],
    ["David Carmo", "Olympiacos", 78, "PT"],
    ["Domagoj Vida", "AEK Athens", 78, "HR"],
    ["Baba Rahman", "PAOK", 77, "GH"],
    ["Santiago Hezze", "Olympiacos", 78, "AR"],
    ["Orbelin Pineda", "AEK Athens", 79, "MX"],
    ["Kostas Fortounis", "Olympiacos", 80, "GR"],
    ["Daniel Podence", "Olympiacos", 79, "PT"],
    ["Ayoub El Kaabi", "Olympiacos", 80, "MA"],
    ["Andrija Zivkovic", "PAOK", 79, "RS"],
    ["Alberto Brignoli", "AEK Athens", 76, "IT"],
    ["Alexandros Paschalakis", "Olympiacos", 77, "GR"],
    ["Giorgos Vagiannidis", "Panathinaikos", 75, "GR"],
    ["Tin Jedvaj", "Panathinaikos", 76, "HR"],
    ["William Troost-Ekong", "PAOK", 76, "NG"],
    ["Juankar", "Panathinaikos", 75, "ES"],
    ["Magomed Ozdoev", "PAOK", 77, "RU"],
    ["Mijat Gacinovic", "AEK Athens", 77, "RS"],
    ["Bernard", "Panathinaikos", 78, "BR"],
    ["Taison", "PAOK", 78, "BR"],
    ["Fotis Ioannidis", "Panathinaikos", 79, "GR"],
    ["Levi Garcia", "AEK Athens", 78, "TT"],
    ["Cedric Bakambu", "Olympiacos", 77, "CD"],
    ["Steven Zuber", "AEK Athens", 77, "CH"],
    ["Willian Arao", "Panathinaikos", 76, "BR"]
  ]),
  "danish-superliga": squad("Danish Superliga", "dk", 9, [
    ["Kamil Grabara", "Copenhagen", 78, "PL"],
    ["Elias Jelert", "Copenhagen", 75, "DK"],
    ["Kevin Diks", "Copenhagen", 77, "NL"],
    ["Denis Vavro", "Copenhagen", 77, "SK"],
    ["Birger Meling", "Copenhagen", 76, "NO"],
    ["Rasmus Falk", "Copenhagen", 77, "DK"],
    ["Mads Bidstrup", "Nordsjaelland", 75, "DK"],
    ["Roony Bardghji", "Copenhagen", 76, "SE"],
    ["Mohamed Elyounoussi", "Copenhagen", 78, "NO"],
    ["German Onugkha", "Copenhagen", 77, "RU"],
    ["Franculino Dju", "Midtjylland", 76, "GW"],
    ["Mads Hermansen", "Brondby", 75, "DK"],
    ["Jesper Hansen", "AGF", 73, "DK"],
    ["Henrik Dalsgaard", "Midtjylland", 74, "DK"],
    ["Ousmane Diao", "Midtjylland", 74, "SN"],
    ["Jacob Rasmussen", "Brondby", 75, "DK"],
    ["Daniel Svensson", "Nordsjaelland", 74, "SE"],
    ["Mathias Jensen", "Brondby", 75, "DK"],
    ["Oliver Sorensen", "Midtjylland", 75, "DK"],
    ["Magnus Mattsson", "Copenhagen", 76, "DK"],
    ["Yuito Suzuki", "Brondby", 76, "JP"],
    ["Andreas Schjelderup", "Nordsjaelland", 76, "NO"],
    ["Patrick Mortensen", "AGF", 75, "DK"],
    ["Ohi Omoijuanfo", "Brondby", 75, "NO"],
    ["Osman Bukari", "Copenhagen", 76, "GH"],
    ["Ernest Nuamah", "Nordsjaelland", 76, "GH"]
  ]),
  "scottish-premiership": squad("Scottish Premiership", "sct", 8, [
    ["Joe Hart", "Celtic", 78, "ENG"],
    ["Alistair Johnston", "Celtic", 76, "CA"],
    ["Cameron Carter-Vickers", "Celtic", 78, "US"],
    ["John Souttar", "Rangers", 75, "SCT"],
    ["Greg Taylor", "Celtic", 76, "SCT"],
    ["Callum McGregor", "Celtic", 79, "SCT"],
    ["Matt O'Riley", "Celtic", 80, "DK"],
    ["Todd Cantwell", "Rangers", 77, "ENG"],
    ["Daizen Maeda", "Celtic", 78, "JP"],
    ["Kyogo Furuhashi", "Celtic", 80, "JP"],
    ["James Tavernier", "Rangers", 79, "ENG"],
    ["Jack Butland", "Rangers", 77, "ENG"],
    ["Kasper Schmeichel", "Celtic", 79, "DK"],
    ["Anthony Ralston", "Celtic", 73, "SCT"],
    ["Connor Goldson", "Rangers", 75, "ENG"],
    ["Liam Scales", "Celtic", 74, "IE"],
    ["Borna Barisic", "Rangers", 75, "HR"],
    ["Nicolas Raskin", "Rangers", 75, "BE"],
    ["Reo Hatate", "Celtic", 78, "JP"],
    ["Tom Lawrence", "Rangers", 76, "WAL"],
    ["Nicolas Kuhn", "Celtic", 77, "DE"],
    ["Cyriel Dessers", "Rangers", 76, "NG"],
    ["Adam Idah", "Celtic", 76, "IE"],
    ["Lawrence Shankland", "Hearts", 77, "SCT"],
    ["Rabbi Matondo", "Rangers", 75, "WAL"],
    ["Luis Palma", "Celtic", 76, "HN"]
  ]),
  "austrian-bundesliga": squad("Austrian Bundesliga", "at", 8, [
    ["Alexander Schlager", "Red Bull Salzburg", 76, "AT"],
    ["Amar Dedic", "Red Bull Salzburg", 77, "BA"],
    ["Oumar Solet", "Red Bull Salzburg", 77, "FR"],
    ["Strahinja Pavlovic", "Red Bull Salzburg", 78, "RS"],
    ["Andreas Ulmer", "Red Bull Salzburg", 74, "AT"],
    ["Nicolas Seiwald", "Red Bull Salzburg", 77, "AT"],
    ["Maurits Kjaergaard", "Red Bull Salzburg", 76, "DK"],
    ["Oscar Gloukh", "Red Bull Salzburg", 78, "IL"],
    ["Karim Konate", "Red Bull Salzburg", 77, "CI"],
    ["Junior Adamu", "Red Bull Salzburg", 75, "AT"],
    ["Manprit Sarkaria", "Sturm Graz", 76, "AT"],
    ["Niklas Hedl", "Rapid Wien", 74, "AT"],
    ["Kjell Scherpen", "Sturm Graz", 74, "NL"],
    ["Stefan Hierlander", "Sturm Graz", 74, "AT"],
    ["David Affengruber", "Sturm Graz", 75, "AT"],
    ["Gregory Wuthrich", "Sturm Graz", 75, "CH"],
    ["Jon Gorenc Stankovic", "Sturm Graz", 75, "SI"],
    ["Alexander Prass", "Sturm Graz", 76, "AT"],
    ["Otar Kiteishvili", "Sturm Graz", 77, "GE"],
    ["Matthias Seidl", "Rapid Wien", 75, "AT"],
    ["Dominik Fitz", "Austria Wien", 75, "AT"],
    ["Marco Grull", "Rapid Wien", 76, "AT"],
    ["Szymon Wlodarczyk", "Sturm Graz", 74, "PL"],
    ["Guido Burgstaller", "Rapid Wien", 76, "AT"],
    ["Mika Biereth", "Sturm Graz", 76, "DK"],
    ["Dorgeles Nene", "Red Bull Salzburg", 75, "CI"]
  ]),
  "swiss-super-league": squad("Swiss Super League", "ch", 8, [
    ["Yvon Mvogo", "Young Boys", 77, "CH"],
    ["Silvan Hefti", "Young Boys", 75, "CH"],
    ["Mohamed Camara", "Young Boys", 75, "ML"],
    ["Fabian Schar", "Basel", 78, "CH"],
    ["Ulisses Garcia", "Young Boys", 75, "CH"],
    ["Granit Xhaka", "Basel", 84, "CH"],
    ["Fabian Rieder", "Young Boys", 77, "CH"],
    ["Xherdan Shaqiri", "Basel", 80, "CH"],
    ["Dan Ndoye", "Basel", 78, "CH"],
    ["Cedric Itten", "Young Boys", 76, "CH"],
    ["Zeki Amdouni", "Basel", 78, "CH"],
    ["Anthony Racioppi", "Young Boys", 74, "CH"],
    ["Marwin Hitz", "Basel", 75, "CH"],
    ["Kevin Ruegg", "Zurich", 73, "CH"],
    ["Aurele Amenda", "Young Boys", 75, "CH"],
    ["Leonidas Stergiou", "St. Gallen", 75, "CH"],
    ["Ricardo Rodriguez", "Zurich", 78, "CH"],
    ["Vincent Sierro", "Sion", 76, "CH"],
    ["Sandro Lauper", "Young Boys", 74, "CH"],
    ["Renato Steffen", "Lugano", 76, "CH"],
    ["Uran Bislimi", "Lugano", 75, "CH"],
    ["Miroslav Stevanovic", "Servette", 75, "BA"],
    ["Jean-Pierre Nsame", "Young Boys", 76, "CM"],
    ["Thierno Barry", "Basel", 76, "FR"],
    ["Dereck Kutesa", "Servette", 75, "CH"],
    ["Christian Fassnacht", "Young Boys", 75, "CH"]
  ]),
  "serbian-superliga": squad("Serbian SuperLiga", "rs", 8, [
    ["Omri Glazer", "Red Star Belgrade", 77, "IL"],
    ["Kosta Nedeljkovic", "Red Star Belgrade", 74, "RS"],
    ["Uros Spajic", "Red Star Belgrade", 76, "RS"],
    ["Svetozar Markovic", "Partizan", 74, "RS"],
    ["Milan Rodic", "Red Star Belgrade", 75, "RS"],
    ["Guelor Kanga", "Red Star Belgrade", 76, "GA"],
    ["Hwang In-beom", "Red Star Belgrade", 78, "KR"],
    ["Mirko Ivanic", "Red Star Belgrade", 78, "RS"],
    ["Osman Bukari", "Red Star Belgrade", 77, "GH"],
    ["Cherif Ndiaye", "Red Star Belgrade", 76, "SN"],
    ["Samed Bazdar", "Partizan", 75, "RS"],
    ["Aleksandar Jovanovic", "Partizan", 74, "RS"],
    ["Nikola Vasiljevic", "Radnicki", 72, "RS"],
    ["Marko Zivkovic", "Partizan", 73, "RS"],
    ["Aleksandar Dragovic", "Red Star Belgrade", 77, "AT"],
    ["Nasser Djiga", "Red Star Belgrade", 75, "BF"],
    ["Slobodan Urosevic", "Partizan", 73, "RS"],
    ["Sasa Zdjelar", "Partizan", 74, "RS"],
    ["Bibras Natcho", "Partizan", 76, "IL"],
    ["Queensy Menig", "Partizan", 75, "NL"],
    ["Aleksandar Katai", "Red Star Belgrade", 77, "RS"],
    ["Peter Olayinka", "Red Star Belgrade", 77, "NG"],
    ["Aldo Kalulu", "Partizan", 74, "FR"],
    ["Jean-Philippe Krasso", "Red Star Belgrade", 76, "CI"],
    ["Mihailo Ivanovic", "Vojvodina", 73, "RS"],
    ["Andrija Zivkovic", "Partizan", 76, "RS"]
  ]),
  "croatian-hnl": squad("Croatian HNL", "hr", 8, [
    ["Dominik Livakovic", "Dinamo Zagreb", 80, "HR"],
    ["Stefan Ristovski", "Dinamo Zagreb", 75, "MK"],
    ["Josip Sutalo", "Dinamo Zagreb", 77, "HR"],
    ["Dino Peric", "Dinamo Zagreb", 74, "HR"],
    ["Borna Sosa", "Dinamo Zagreb", 78, "HR"],
    ["Josip Misic", "Dinamo Zagreb", 77, "HR"],
    ["Martin Baturina", "Dinamo Zagreb", 79, "HR"],
    ["Bruno Petkovic", "Dinamo Zagreb", 80, "HR"],
    ["Luka Ivanusec", "Dinamo Zagreb", 78, "HR"],
    ["Marko Livaja", "Hajduk Split", 79, "HR"],
    ["Mislav Orsic", "Dinamo Zagreb", 78, "HR"],
    ["Lovre Kalinic", "Hajduk Split", 75, "HR"],
    ["Ivan Nevistic", "Dinamo Zagreb", 74, "HR"],
    ["Josip Juranovic", "Dinamo Zagreb", 77, "HR"],
    ["Ferro", "Hajduk Split", 74, "PT"],
    ["Dominik Prpic", "Hajduk Split", 73, "HR"],
    ["Dario Melnjak", "Hajduk Split", 74, "HR"],
    ["Arijan Ademi", "Dinamo Zagreb", 76, "MK"],
    ["Lukas Kacavenda", "Dinamo Zagreb", 75, "HR"],
    ["Niko Sigur", "Hajduk Split", 74, "HR"],
    ["Ivan Perisic", "Hajduk Split", 80, "HR"],
    ["Sandro Kulenovic", "Dinamo Zagreb", 75, "HR"],
    ["Dion Drena Beljo", "Dinamo Zagreb", 75, "HR"],
    ["Ramon Mierez", "Osijek", 76, "AR"],
    ["Marco Pasalic", "Rijeka", 75, "HR"],
    ["Toni Fruk", "Rijeka", 75, "HR"]
  ]),
  "ukrainian-premier-league": squad("Ukrainian Premier League", "ua", 8, [
    ["Anatoliy Trubin", "Shakhtar Donetsk", 80, "UA"],
    ["Yukhym Konoplya", "Shakhtar Donetsk", 75, "UA"],
    ["Mykola Matviyenko", "Shakhtar Donetsk", 78, "UA"],
    ["Denys Popov", "Dynamo Kyiv", 75, "UA"],
    ["Vitaliy Mykolenko", "Dynamo Kyiv", 79, "UA"],
    ["Taras Stepanenko", "Shakhtar Donetsk", 76, "UA"],
    ["Mykola Shaparenko", "Dynamo Kyiv", 77, "UA"],
    ["Georgiy Sudakov", "Shakhtar Donetsk", 80, "UA"],
    ["Oleksandr Zubkov", "Shakhtar Donetsk", 77, "UA"],
    ["Vladyslav Vanat", "Dynamo Kyiv", 78, "UA"],
    ["Danylo Sikan", "Shakhtar Donetsk", 76, "UA"],
    ["Heorhiy Bushchan", "Dynamo Kyiv", 77, "UA"],
    ["Dmytro Riznyk", "Shakhtar Donetsk", 76, "UA"],
    ["Oleksandr Tymchyk", "Dynamo Kyiv", 74, "UA"],
    ["Valeriy Bondar", "Shakhtar Donetsk", 75, "UA"],
    ["Illia Zabarnyi", "Dynamo Kyiv", 80, "UA"],
    ["Bohdan Mykhaylichenko", "Polissya Zhytomyr", 74, "UA"],
    ["Volodymyr Brazhko", "Dynamo Kyiv", 76, "UA"],
    ["Artem Bondarenko", "Shakhtar Donetsk", 76, "UA"],
    ["Viktor Tsygankov", "Dynamo Kyiv", 80, "UA"],
    ["Andriy Yarmolenko", "Dynamo Kyiv", 78, "UA"],
    ["Mykhailo Mudryk", "Shakhtar Donetsk", 79, "UA"],
    ["Artem Dovbyk", "Dnipro-1", 80, "UA"],
    ["Maksym Talovierov", "LNZ Cherkasy", 74, "UA"],
    ["Nazariy Rusyn", "Zorya Luhansk", 74, "UA"],
    ["Oleksandr Pikhalyonok", "Dynamo Kyiv", 76, "UA"]
  ]),
  ekstraklasa: squad("Ekstraklasa", "plk", 8, [
    ["Kacper Tobiasz", "Legia Warsaw", 74, "PL"],
    ["Bartosz Bereszynski", "Lech Poznan", 75, "PL"],
    ["Artur Jedrzejczyk", "Legia Warsaw", 74, "PL"],
    ["Mikael Ishak", "Lech Poznan", 76, "SE"],
    ["Tymoteusz Puchacz", "Lech Poznan", 75, "PL"],
    ["Bartosz Slisz", "Legia Warsaw", 75, "PL"],
    ["Filip Marchwinski", "Lech Poznan", 75, "PL"],
    ["Josue", "Legia Warsaw", 77, "PT"],
    ["Kamil Grosicki", "Pogon Szczecin", 77, "PL"],
    ["Jesus Imaz", "Jagiellonia Bialystok", 76, "ES"],
    ["Afimico Pululu", "Jagiellonia Bialystok", 75, "AO"],
    ["Vladan Kovacevic", "Rakow Czestochowa", 75, "BA"],
    ["Frantisek Plach", "Piast Gliwice", 73, "SK"],
    ["Patryk Kun", "Legia Warsaw", 73, "PL"],
    ["Steve Kapuadi", "Legia Warsaw", 73, "FR"],
    ["Bogdan Racovitan", "Rakow Czestochowa", 74, "RO"],
    ["Jean Carlos Silva", "Rakow Czestochowa", 74, "ES"],
    ["Damian Dombrowski", "Pogon Szczecin", 73, "PL"],
    ["Taras Romanczuk", "Jagiellonia Bialystok", 74, "PL"],
    ["Nene", "Jagiellonia Bialystok", 74, "PT"],
    ["Kristoffer Velde", "Lech Poznan", 75, "NO"],
    ["Erik Exposito", "Slask Wroclaw", 76, "ES"],
    ["Efthymios Koulouris", "Pogon Szczecin", 75, "GR"],
    ["Marc Gual", "Legia Warsaw", 74, "ES"],
    ["Pedro Nuno", "Korona Kielce", 73, "PT"],
    ["Kajetan Szmyt", "Warta Poznan", 73, "PL"]
  ]),
  "categoria-primera-a": squad("Categoria Primera A", "co", 8, [
    ["Alvaro Montero", "Millonarios", 76, "CO"],
    ["Daniel Munoz", "Atletico Nacional", 77, "CO"],
    ["Andres Llinas", "Millonarios", 75, "CO"],
    ["William Tesillo", "Atletico Nacional", 75, "CO"],
    ["Danovis Banguero", "Atletico Nacional", 74, "CO"],
    ["Jorman Campuzano", "Atletico Nacional", 75, "CO"],
    ["Daniel Ruiz", "Millonarios", 76, "CO"],
    ["Juan Fernando Quintero", "America de Cali", 80, "CO"],
    ["Edwin Cardona", "Atletico Nacional", 77, "CO"],
    ["Hugo Rodallega", "Santa Fe", 78, "CO"],
    ["Dayro Moreno", "Once Caldas", 78, "CO"],
    ["Kevin Mier", "Atletico Nacional", 76, "CO"],
    ["Jose Luis Chunga", "Junior", 74, "CO"],
    ["Yerson Candelo", "Atletico Nacional", 74, "CO"],
    ["Carlos Cuesta", "Atletico Nacional", 76, "CO"],
    ["Davinson Sanchez", "Atletico Nacional", 80, "CO"],
    ["Frank Fabra", "Deportivo Cali", 76, "CO"],
    ["Sebastian Gomez", "Atletico Nacional", 75, "CO"],
    ["Larry Vasquez", "Millonarios", 74, "CO"],
    ["Yimmi Chara", "Junior", 76, "CO"],
    ["Macnelly Torres", "Atletico Nacional", 75, "CO"],
    ["Carlos Bacca", "Junior", 78, "CO"],
    ["Miguel Borja", "Junior", 79, "CO"],
    ["Leonardo Castro", "Millonarios", 76, "CO"],
    ["Jader Valencia", "Millonarios", 73, "CO"],
    ["Duvan Vergara", "America de Cali", 76, "CO"]
  ]),
  "primera-paraguay": squad("Primera Division Paraguay", "py", 8, [
    ["Gatito Fernandez", "Cerro Porteno", 76, "PY"],
    ["Alan Benitez", "Cerro Porteno", 74, "PY"],
    ["Gustavo Gomez", "Libertad", 80, "PY"],
    ["Fabian Balbuena", "Libertad", 78, "PY"],
    ["Ivan Torres", "Olimpia", 73, "PY"],
    ["Richard Ortiz", "Olimpia", 76, "PY"],
    ["Mathias Villasanti", "Cerro Porteno", 77, "PY"],
    ["Diego Gomez", "Libertad", 77, "PY"],
    ["Miguel Almiron", "Cerro Porteno", 80, "PY"],
    ["Roque Santa Cruz", "Libertad", 76, "PY"],
    ["Antonio Bareiro", "Libertad", 75, "PY"],
    ["Martin Silva", "Libertad", 75, "UY"],
    ["Jean Fernandes", "Cerro Porteno", 75, "BR"],
    ["Robert Rojas", "Olimpia", 75, "PY"],
    ["Junior Alonso", "Cerro Porteno", 77, "PY"],
    ["Luis Cardozo", "Olimpia", 73, "PY"],
    ["Santiago Arzamendia", "Cerro Porteno", 75, "PY"],
    ["Angel Cardozo Lucena", "Cerro Porteno", 74, "PY"],
    ["Hernesto Caballero", "Libertad", 73, "PY"],
    ["Derlis Gonzalez", "Olimpia", 76, "PY"],
    ["Oscar Romero", "Cerro Porteno", 77, "PY"],
    ["Lorenzo Melgarejo", "Libertad", 75, "PY"],
    ["Alex Arce", "Olimpia", 76, "PY"],
    ["Isidro Pitta", "Olimpia", 75, "PY"],
    ["Cecilio Dominguez", "Cerro Porteno", 76, "PY"],
    ["Matias Espinoza", "Libertad", 73, "PY"]
  ]),
  "ligapro-ecuador": squad("LigaPro Ecuador", "ec", 8, [
    ["Alexander Dominguez", "LDU Quito", 76, "EC"],
    ["Byron Castillo", "Barcelona SC", 75, "EC"],
    ["Piero Hincapie", "Independiente del Valle", 80, "EC"],
    ["Robert Arboleda", "Sao Paulo", 78, "EC"],
    ["Leonel Quinonez", "Barcelona SC", 74, "EC"],
    ["Dixon Arroyo", "Barcelona SC", 74, "EC"],
    ["Moises Caicedo", "Independiente del Valle", 83, "EC"],
    ["Junior Sornoza", "Independiente del Valle", 77, "EC"],
    ["Kendry Paez", "Independiente del Valle", 78, "EC"],
    ["Enner Valencia", "Emelec", 80, "EC"],
    ["Michael Estrada", "LDU Quito", 75, "EC"],
    ["Hernan Galindez", "Aucas", 75, "EC"],
    ["Javier Burrai", "Barcelona SC", 74, "AR"],
    ["Angelo Preciado", "Independiente del Valle", 76, "EC"],
    ["Felix Torres", "Barcelona SC", 76, "EC"],
    ["Luis Leon", "LDU Quito", 73, "EC"],
    ["Beder Caicedo", "Independiente del Valle", 73, "EC"],
    ["Carlos Gruezo", "LDU Quito", 76, "EC"],
    ["Jhegson Mendez", "Independiente del Valle", 75, "EC"],
    ["Damian Diaz", "Barcelona SC", 75, "AR"],
    ["Joao Rojas", "Barcelona SC", 75, "EC"],
    ["Jose Cifuentes", "LDU Quito", 76, "EC"],
    ["Leonardo Campana", "Barcelona SC", 76, "EC"],
    ["Djorkaeff Reasco", "LDU Quito", 73, "EC"],
    ["Adonis Preciado", "Barcelona SC", 74, "EC"],
    ["Lautaro Diaz", "Independiente del Valle", 75, "AR"]
  ]),
  "egyptian-premier-league": squad("Egyptian Premier League", "eg", 8, [
    ["Mohamed El Shenawy", "Al Ahly", 78, "EG"],
    ["Mohamed Hany", "Al Ahly", 75, "EG"],
    ["Mohamed Abdelmonem", "Al Ahly", 77, "EG"],
    ["Mahmoud Hamdy", "Zamalek", 75, "EG"],
    ["Ali Maaloul", "Al Ahly", 77, "TN"],
    ["Marwan Attia", "Al Ahly", 75, "EG"],
    ["Emam Ashour", "Al Ahly", 77, "EG"],
    ["Afsha", "Al Ahly", 76, "EG"],
    ["Zizo", "Zamalek", 79, "EG"],
    ["Mostafa Mohamed", "Zamalek", 78, "EG"],
    ["Percy Tau", "Al Ahly", 78, "ZA"],
    ["Mohamed Awad", "Zamalek", 75, "EG"],
    ["Mahmoud Gad", "Al Masry", 73, "EG"],
    ["Omar Gaber", "Zamalek", 74, "EG"],
    ["Yasser Ibrahim", "Al Ahly", 75, "EG"],
    ["Hamza Mathlouthi", "Zamalek", 74, "TN"],
    ["Ahmed Fatouh", "Zamalek", 75, "EG"],
    ["Hamdi Fathi", "Al Ahly", 76, "EG"],
    ["Nabil Emad Dunga", "Zamalek", 74, "EG"],
    ["Ramadan Sobhi", "Pyramids", 77, "EG"],
    ["Ibrahim Adel", "Pyramids", 76, "EG"],
    ["Fiston Mayele", "Pyramids", 76, "CD"],
    ["Kahraba", "Al Ahly", 75, "EG"],
    ["Seifeddine Jaziri", "Zamalek", 75, "TN"],
    ["Hussein El Shahat", "Al Ahly", 76, "EG"],
    ["Taher Mohamed", "Al Ahly", 74, "EG"]
  ]),
  "j1-league": squad("J1 League", "jp", 8, [
    ["Zion Suzuki", "Urawa Red Diamonds", 76, "JP"],
    ["Hiroki Sakai", "Urawa Red Diamonds", 77, "JP"],
    ["Shogo Taniguchi", "Kawasaki Frontale", 76, "JP"],
    ["Ko Itakura", "Kawasaki Frontale", 78, "JP"],
    ["Yuto Nagatomo", "FC Tokyo", 75, "JP"],
    ["Ao Tanaka", "Kawasaki Frontale", 77, "JP"],
    ["Hotaru Yamaguchi", "Vissel Kobe", 75, "JP"],
    ["Yoshinori Muto", "Vissel Kobe", 76, "JP"],
    ["Takuma Asano", "Sanfrecce Hiroshima", 76, "JP"],
    ["Yuya Osako", "Vissel Kobe", 78, "JP"],
    ["Andres Iniesta", "Vissel Kobe", 78, "ES"],
    ["Daiya Maekawa", "Vissel Kobe", 74, "JP"],
    ["Yohei Takaoka", "Yokohama F. Marinos", 74, "JP"],
    ["Miki Yamane", "Kawasaki Frontale", 75, "JP"],
    ["Yuki Kobayashi", "Celtic", 74, "JP"],
    ["Tomoki Iwata", "Yokohama F. Marinos", 75, "JP"],
    ["Yuta Nakayama", "Kashiwa Reysol", 75, "JP"],
    ["Ryota Oshima", "Kawasaki Frontale", 74, "JP"],
    ["Kento Misao", "Kashima Antlers", 74, "JP"],
    ["Takahiro Sekine", "Urawa Red Diamonds", 73, "JP"],
    ["Mateus", "Nagoya Grampus", 75, "BR"],
    ["Leandro Damiao", "Kawasaki Frontale", 76, "BR"],
    ["Patric", "Nagoya Grampus", 74, "BR"],
    ["Shinzo Koroki", "Urawa Red Diamonds", 74, "JP"],
    ["Elber", "Yokohama F. Marinos", 75, "BR"],
    ["Lopes", "Yokohama F. Marinos", 75, "BR"]
  ]),
  "k-league-1": squad("K League 1", "kr", 8, [
    ["Jo Hyeon-woo", "Ulsan HD", 76, "KR"],
    ["Kim Tae-hwan", "Ulsan HD", 74, "KR"],
    ["Kim Young-gwon", "Ulsan HD", 76, "KR"],
    ["Jeong Seung-hyun", "Ulsan HD", 75, "KR"],
    ["Lee Myung-jae", "Ulsan HD", 73, "KR"],
    ["Park Yong-woo", "Ulsan HD", 74, "KR"],
    ["Paik Seung-ho", "Jeonbuk Hyundai", 76, "KR"],
    ["Lee Chung-yong", "Ulsan HD", 75, "KR"],
    ["Um Won-sang", "Ulsan HD", 75, "KR"],
    ["Cho Gue-sung", "Jeonbuk Hyundai", 76, "KR"],
    ["Na Sang-ho", "FC Seoul", 75, "KR"],
    ["Song Bum-keun", "Jeonbuk Hyundai", 74, "KR"],
    ["Yang Han-been", "FC Seoul", 73, "KR"],
    ["Kim Moon-hwan", "Jeonbuk Hyundai", 74, "KR"],
    ["Hong Jeong-ho", "Jeonbuk Hyundai", 75, "KR"],
    ["Dave Bulthuis", "Ulsan HD", 73, "NL"],
    ["Kim Jin-su", "Jeonbuk Hyundai", 75, "KR"],
    ["Ki Sung-yueng", "FC Seoul", 76, "KR"],
    ["Han Kook-young", "Gangwon FC", 73, "KR"],
    ["Cesinha", "Daegu FC", 77, "BR"],
    ["Gustav Ludwigson", "Ulsan HD", 74, "SE"],
    ["Joo Min-kyu", "Ulsan HD", 76, "KR"],
    ["Stanislav Iljutcenko", "FC Seoul", 75, "DE"],
    ["Gerso Fernandes", "Incheon United", 74, "GW"],
    ["Willyan", "FC Seoul", 74, "BR"],
    ["Valeri Qazaishvili", "Ulsan HD", 75, "GE"]
  ]),
  "uae-pro-league": squad("UAE Pro League", "ae", 8, [
    ["Khalid Eisa", "Al Ain", 75, "AE"],
    ["Bandar Al Ahbabi", "Al Ain", 75, "AE"],
    ["Kouame Autonne", "Al Ain", 74, "CI"],
    ["Khalifa Al Hammadi", "Al Jazira", 73, "AE"],
    ["Erik", "Al Ain", 74, "BR"],
    ["Yahya Nader", "Al Ain", 73, "AE"],
    ["Abdoulaye Toure", "Al Jazira", 76, "GN"],
    ["Alejandro Romero Gamarra", "Al Ain", 77, "PY"],
    ["Kodjo Laba", "Al Ain", 78, "TG"],
    ["Ali Mabkhout", "Al Jazira", 78, "AE"],
    ["Sofiane Rahimi", "Al Ain", 79, "MA"],
    ["Ali Khaseif", "Al Jazira", 73, "AE"],
    ["Fahad Al Dhanhani", "Baniyas", 72, "AE"],
    ["Hazza Al Hammadi", "Al Ain", 72, "AE"],
    ["Sasa Ivkovic", "Baniyas", 72, "RS"],
    ["Milos Kosanovic", "Al Jazira", 73, "RS"],
    ["Abdelaziz Sanqour", "Shabab Al Ahli", 72, "AE"],
    ["Federico Cartabia", "Shabab Al Ahli", 76, "AR"],
    ["Caio Canedo", "Al Wasl", 75, "AE"],
    ["Lima", "Al Wasl", 75, "BR"],
    ["Omar Abdulrahman", "Al Wasl", 76, "AE"],
    ["Gaston Suarez", "Baniyas", 73, "AR"],
    ["Fabio Lima", "Al Wasl", 76, "AE"],
    ["Igor Jesus", "Shabab Al Ahli", 75, "BR"],
    ["Haris Seferovic", "Al Wasl", 76, "CH"],
    ["Mehdi Ghayedi", "Shabab Al Ahli", 75, "IR"]
  ]),
  "botola-pro": squad("Botola Pro", "ma", 8, [
    ["Anas Zniti", "Raja Casablanca", 75, "MA"],
    ["Ayoub El Amloud", "Wydad AC", 74, "MA"],
    ["Yahya Jabrane", "Wydad AC", 76, "MA"],
    ["Achraf Dari", "Wydad AC", 76, "MA"],
    ["Yahya Attiat-Allah", "Wydad AC", 76, "MA"],
    ["Mohamed Rabie Hrimat", "AS FAR", 75, "MA"],
    ["Walid El Karti", "Wydad AC", 76, "MA"],
    ["Ismail El Haddad", "Wydad AC", 75, "MA"],
    ["Soufiane Rahimi", "Raja Casablanca", 78, "MA"],
    ["Hamid Ahaddad", "Raja Casablanca", 74, "MA"],
    ["Mouhcine Iajour", "Raja Casablanca", 74, "MA"],
    ["Ahmed Reda Tagnaouti", "Wydad AC", 74, "MA"],
    ["Yassine Bounou", "Wydad AC", 80, "MA"],
    ["Mohamed Nahiri", "Raja Casablanca", 73, "MA"],
    ["Badr Benoun", "Raja Casablanca", 75, "MA"],
    ["Marouane Saadane", "FAR Rabat", 74, "MA"],
    ["Abdelilah Madkour", "Raja Casablanca", 73, "MA"],
    ["Zakaria Draoui", "Wydad AC", 74, "MA"],
    ["Reda Slim", "AS FAR", 75, "MA"],
    ["Mohamed Ounajem", "Wydad AC", 75, "MA"],
    ["Ayoub Nanah", "Raja Casablanca", 73, "MA"],
    ["Ayoub El Kaabi", "Wydad AC", 74, "MA"],
    ["Mehdi Benabid", "AS FAR", 73, "MA"],
    ["Karim El Berkaoui", "Hassania Agadir", 74, "MA"],
    ["Zakaria Hadraf", "Raja Casablanca", 74, "MA"],
    ["Houcine Rahimi", "Raja Casablanca", 73, "MA"]
  ]),
  "romanian-superliga": squad("Romanian SuperLiga", "ro", 8, [
    ["Stefan Tarnovanu", "FCSB", 74, "RO"],
    ["Valentin Cretu", "FCSB", 72, "RO"],
    ["Joyskim Dawa", "FCSB", 74, "CM"],
    ["Andrei Burca", "CFR Cluj", 74, "RO"],
    ["Mario Camora", "CFR Cluj", 73, "RO"],
    ["Darius Olaru", "FCSB", 76, "RO"],
    ["Adrian Sut", "FCSB", 74, "RO"],
    ["Alexandru Cicaldau", "Universitatea Craiova", 75, "RO"],
    ["Florinel Coman", "FCSB", 77, "RO"],
    ["Daniel Birligea", "CFR Cluj", 75, "RO"],
    ["Louis Munteanu", "Farul Constanta", 75, "RO"],
    ["Horatiu Moldovan", "Rapid Bucuresti", 75, "RO"],
    ["Cristian Balgradean", "CFR Cluj", 73, "RO"],
    ["Cristian Manea", "CFR Cluj", 73, "RO"],
    ["Ionut Nedelcearu", "FCSB", 74, "RO"],
    ["Mihai Popescu", "Farul Constanta", 72, "RO"],
    ["Nicu Bancu", "Universitatea Craiova", 75, "RO"],
    ["Damjan Djokovic", "Rapid Bucuresti", 74, "HR"],
    ["Alexandru Mitrita", "Universitatea Craiova", 76, "RO"],
    ["Constantin Budescu", "Farul Constanta", 74, "RO"],
    ["Octavian Popescu", "FCSB", 75, "RO"],
    ["Denis Alibec", "Farul Constanta", 76, "RO"],
    ["Andrea Compagno", "FCSB", 74, "IT"],
    ["Rangelo Janga", "CFR Cluj", 73, "CW"],
    ["Jayson Papeau", "Rapid Bucuresti", 73, "FR"],
    ["Dennis Man", "FCSB", 76, "RO"]
  ]),
  "israeli-premier-league": squad("Israeli Premier League", "il", 8, [
    ["Daniel Peretz", "Maccabi Tel Aviv", 76, "IL"],
    ["Eli Dasa", "Maccabi Tel Aviv", 75, "IL"],
    ["Miguel Vitor", "Hapoel Be'er Sheva", 75, "IL"],
    ["Sean Goldberg", "Maccabi Haifa", 74, "IL"],
    ["Sun Menachem", "Maccabi Haifa", 73, "IL"],
    ["Neta Lavi", "Maccabi Haifa", 75, "IL"],
    ["Mohammad Abu Fani", "Maccabi Haifa", 75, "IL"],
    ["Oscar Gloukh", "Maccabi Tel Aviv", 78, "IL"],
    ["Eran Zahavi", "Maccabi Tel Aviv", 78, "IL"],
    ["Frantzdy Pierrot", "Maccabi Haifa", 76, "HT"],
    ["Lior Refaelov", "Maccabi Haifa", 76, "IL"],
    ["Josh Cohen", "Maccabi Haifa", 74, "US"],
    ["Omri Glazer", "Hapoel Be'er Sheva", 74, "IL"],
    ["Dolev Haziza", "Maccabi Haifa", 74, "IL"],
    ["Abdoulaye Seck", "Maccabi Haifa", 74, "SN"],
    ["Raz Shlomo", "Maccabi Tel Aviv", 73, "IL"],
    ["Ofir Davidzada", "Maccabi Tel Aviv", 72, "IL"],
    ["Dor Peretz", "Maccabi Tel Aviv", 75, "IL"],
    ["Gabi Kanichowsky", "Maccabi Tel Aviv", 74, "IL"],
    ["Tjaronn Chery", "Maccabi Haifa", 76, "NL"],
    ["Dia Saba", "Maccabi Haifa", 75, "IL"],
    ["Dor Turgeman", "Maccabi Tel Aviv", 74, "IL"],
    ["Dean David", "Maccabi Haifa", 74, "IL"],
    ["Itamar Shviro", "Maccabi Tel Aviv", 72, "IL"],
    ["Omer Atzili", "Maccabi Haifa", 76, "IL"],
    ["Anan Khalaili", "Maccabi Haifa", 75, "IL"]
  ]),
  eliteserien: squad("Eliteserien", "no", 8, [
    ["Andre Hansen", "Rosenborg", 74, "NO"],
    ["Omar Elabdellaoui", "Bodo/Glimt", 74, "NO"],
    ["Brede Moe", "Bodo/Glimt", 73, "NO"],
    ["Marius Lode", "Bodo/Glimt", 73, "NO"],
    ["Fredrik Bjorkan", "Bodo/Glimt", 74, "NO"],
    ["Patrick Berg", "Bodo/Glimt", 76, "NO"],
    ["Sivert Mannsverk", "Molde", 74, "NO"],
    ["Amahl Pellegrino", "Bodo/Glimt", 76, "NO"],
    ["Hugo Vetlesen", "Bodo/Glimt", 75, "NO"],
    ["Ola Brynhildsen", "Molde", 74, "NO"],
    ["Kasper Hogh", "Bodo/Glimt", 74, "DK"],
    ["Nikita Haikin", "Bodo/Glimt", 73, "RU"],
    ["Jacob Karlstrom", "Molde", 72, "SE"],
    ["Julian Ryerson", "Viking", 75, "NO"],
    ["Sheriff Sinyan", "Molde", 72, "GM"],
    ["Anders Hagelskjaer", "Molde", 72, "DK"],
    ["Birger Meling", "Rosenborg", 74, "NO"],
    ["Markus Henriksen", "Rosenborg", 74, "NO"],
    ["Emil Breivik", "Molde", 73, "NO"],
    ["Zlatko Tripic", "Viking", 74, "NO"],
    ["Carlo Holse", "Rosenborg", 74, "DK"],
    ["Leke James", "Molde", 73, "NG"],
    ["Veton Berisha", "Molde", 74, "NO"],
    ["Bard Finne", "Brann", 74, "NO"],
    ["Albert Gronbaek", "Bodo/Glimt", 75, "DK"],
    ["Joel Mvuka", "Bodo/Glimt", 73, "NO"]
  ]),
  allsvenskan: squad("Allsvenskan", "se", 8, [
    ["Johan Dahlin", "Malmo FF", 74, "SE"],
    ["Felix Beijmo", "Malmo FF", 72, "SE"],
    ["Pontus Jansson", "Malmo FF", 76, "SE"],
    ["Isak Hien", "Djurgarden", 75, "SE"],
    ["Martin Olsson", "Malmo FF", 73, "SE"],
    ["Anders Christiansen", "Malmo FF", 76, "DK"],
    ["Sebastian Nanasi", "Malmo FF", 75, "SE"],
    ["Gustav Berggren", "Djurgarden", 73, "SE"],
    ["Taha Ali", "Malmo FF", 74, "SE"],
    ["Isaac Kiese Thelin", "Malmo FF", 75, "SE"],
    ["Jordan Larsson", "AIK", 75, "SE"],
    ["Jacob Rinne", "Djurgarden", 73, "SE"],
    ["Kristoffer Nordfeldt", "AIK", 73, "SE"],
    ["Joel Andersson", "Hacken", 72, "SE"],
    ["Carl Starfelt", "IFK Goteborg", 75, "SE"],
    ["Hjalmar Ekdal", "Djurgarden", 74, "SE"],
    ["Ludwig Augustinsson", "Malmo FF", 75, "SE"],
    ["Oscar Lewicki", "Malmo FF", 72, "SE"],
    ["Samuel Gustafson", "Hacken", 74, "SE"],
    ["Nahir Besara", "Hammarby", 74, "SE"],
    ["Oliver Berg", "Djurgarden", 73, "SE"],
    ["Marcus Berg", "IFK Goteborg", 74, "SE"],
    ["Christoffer Nyman", "Norrkoping", 74, "SE"],
    ["Alexander Jeremejeff", "Hacken", 74, "SE"],
    ["Viktor Claesson", "Malmo FF", 75, "SE"],
    ["Mikkel Rygaard", "Hacken", 74, "DK"]
  ]),
  "primera-chile": squad("Primera Division Chile", "cl", 8, [
    ["Brayan Cortes", "Colo-Colo", 75, "CL"],
    ["Mauricio Isla", "Colo-Colo", 75, "CL"],
    ["Matias Zaldivia", "Universidad de Chile", 73, "CL"],
    ["Alan Saldivia", "Colo-Colo", 73, "UY"],
    ["Gabriel Suazo", "Colo-Colo", 75, "CL"],
    ["Esteban Pavez", "Colo-Colo", 74, "CL"],
    ["Charles Aranguiz", "Universidad de Chile", 78, "CL"],
    ["Arturo Vidal", "Colo-Colo", 78, "CL"],
    ["Lucas Assadi", "Universidad de Chile", 73, "CL"],
    ["Fernando Zampedri", "Universidad Catolica", 76, "AR"],
    ["Carlos Palacios", "Colo-Colo", 76, "CL"],
    ["Cristopher Toselli", "Universidad de Chile", 72, "CL"],
    ["Fernando De Paul", "Colo-Colo", 72, "AR"],
    ["Oscar Opazo", "Colo-Colo", 73, "CL"],
    ["Gary Medel", "Universidad Catolica", 76, "CL"],
    ["Benjamin Kuscevic", "Universidad Catolica", 74, "CL"],
    ["Eugenio Mena", "Universidad Catolica", 74, "CL"],
    ["Cesar Fuentes", "Colo-Colo", 72, "CL"],
    ["Leonardo Gil", "Colo-Colo", 74, "AR"],
    ["Matias Fernandez", "Colo-Colo", 73, "CL"],
    ["Dario Osorio", "Universidad de Chile", 75, "CL"],
    ["Leandro Fernandez", "Universidad de Chile", 74, "AR"],
    ["Diego Valencia", "Universidad Catolica", 73, "CL"],
    ["Maximiliano Guerrero", "Universidad de Chile", 73, "CL"],
    ["Cristian Zavala", "Colo-Colo", 73, "CL"],
    ["Alexander Aravena", "Universidad Catolica", 74, "CL"]
  ]),
  "primera-uruguay": squad("Primera Division Uruguay", "uy", 8, [
    ["Martin Campana", "Defensor Sporting", 74, "UY"],
    ["Guillermo Varela", "Penarol", 75, "UY"],
    ["Sebastian Coates", "Nacional", 78, "UY"],
    ["Diego Polenta", "Nacional", 74, "UY"],
    ["Joaquin Piquerez", "Penarol", 76, "UY"],
    ["Felipe Carballo", "Nacional", 75, "UY"],
    ["Federico Valverde", "Penarol", 85, "UY"],
    ["Giorgian De Arrascaeta", "Defensor Sporting", 80, "UY"],
    ["Facundo Torres", "Penarol", 77, "UY"],
    ["Luis Suarez", "Nacional", 81, "UY"],
    ["Agustin Canobbio", "Penarol", 76, "UY"],
    ["Kevin Dawson", "Penarol", 74, "UY"],
    ["Sergio Rochet", "Nacional", 76, "UY"],
    ["Giovanni Gonzalez", "Penarol", 74, "UY"],
    ["Jose Maria Gimenez", "Danubio", 80, "UY"],
    ["Matias Vina", "Nacional", 77, "UY"],
    ["Lucas Olaza", "Nacional", 75, "UY"],
    ["Manuel Ugarte", "Fenix", 80, "UY"],
    ["Rodrigo Bentancur", "Boca Juniors", 79, "UY"],
    ["Nicolas De La Cruz", "Liverpool Montevideo", 79, "UY"],
    ["Brian Rodriguez", "Penarol", 75, "UY"],
    ["Darwin Nunez", "Penarol", 82, "UY"],
    ["Maximiliano Gomez", "Defensor Sporting", 76, "UY"],
    ["Jonathan Rodriguez", "Penarol", 76, "UY"],
    ["Brian Ocampo", "Nacional", 74, "UY"],
    ["Ignacio Laquintana", "Penarol", 73, "UY"]
  ]),
  "liga-1-peru": squad("Liga 1 Peru", "pe", 8, [
    ["Pedro Gallese", "Alianza Lima", 76, "PE"],
    ["Luis Advincula", "Sporting Cristal", 77, "PE"],
    ["Carlos Zambrano", "Alianza Lima", 76, "PE"],
    ["Aldo Corzo", "Universitario", 73, "PE"],
    ["Miguel Trauco", "Universitario", 75, "PE"],
    ["Yoshimar Yotun", "Sporting Cristal", 76, "PE"],
    ["Renato Tapia", "Sporting Cristal", 77, "PE"],
    ["Edison Flores", "Universitario", 76, "PE"],
    ["Andy Polo", "Universitario", 74, "PE"],
    ["Paolo Guerrero", "Alianza Lima", 76, "PE"],
    ["Bryan Reyna", "Alianza Lima", 74, "PE"],
    ["Jose Carvallo", "Universitario", 72, "PE"],
    ["Alejandro Duarte", "Sporting Cristal", 72, "PE"],
    ["Jhilmar Lora", "Sporting Cristal", 72, "PE"],
    ["Alexander Callens", "Sport Boys", 76, "PE"],
    ["Luis Abram", "Sporting Cristal", 75, "PE"],
    ["Nilson Loyola", "Sporting Cristal", 72, "PE"],
    ["Sergio Pena", "Alianza Lima", 75, "PE"],
    ["Christofer Gonzales", "Sporting Cristal", 74, "PE"],
    ["Jairo Concha", "Universitario", 73, "PE"],
    ["Piero Quispe", "Universitario", 75, "PE"],
    ["Alex Valera", "Universitario", 74, "PE"],
    ["Hernan Barcos", "Alianza Lima", 75, "AR"],
    ["Irven Avila", "Sporting Cristal", 72, "PE"],
    ["Joao Grimaldo", "Sporting Cristal", 74, "PE"],
    ["Gabriel Costa", "Alianza Lima", 73, "PE"]
  ]),
  "ligue-professionnelle-1-algeria": squad("Ligue Professionnelle 1 Algeria", "dz", 8, [
    ["Alexis Guendouz", "CR Belouizdad", 74, "DZ"],
    ["Houari Ferhani", "JS Kabylie", 71, "DZ"],
    ["Djamel Benlamri", "MC Alger", 75, "DZ"],
    ["Ayoub Abdellaoui", "MC Alger", 73, "DZ"],
    ["Ilyes Chetti", "MC Alger", 72, "DZ"],
    ["Zakaria Draoui", "MC Alger", 73, "DZ"],
    ["Sofiane Bendebka", "MC Alger", 74, "DZ"],
    ["Youcef Belaili", "MC Alger", 77, "DZ"],
    ["Zinedine Ferhat", "MC Alger", 75, "DZ"],
    ["Islam Slimani", "CR Belouizdad", 77, "DZ"],
    ["Baghdad Bounedjah", "JS Saoura", 77, "DZ"],
    ["Rais M'Bolhi", "CR Belouizdad", 74, "DZ"],
    ["Oussama Benbot", "USM Alger", 72, "DZ"],
    ["Hocine Benayada", "CR Belouizdad", 73, "DZ"],
    ["Chouaib Keddad", "CR Belouizdad", 72, "DZ"],
    ["Nabil Lamara", "CR Belouizdad", 71, "DZ"],
    ["Abdelkader Bedrane", "ES Setif", 73, "DZ"],
    ["Amir Sayoud", "CR Belouizdad", 74, "DZ"],
    ["Abderrahmane Meziane", "USM Alger", 73, "DZ"],
    ["Akram Djahnit", "ES Setif", 72, "DZ"],
    ["Abdelmoumene Djabou", "ES Setif", 72, "DZ"],
    ["Karim Aribi", "CR Belouizdad", 72, "DZ"],
    ["Aimen Mahious", "USM Alger", 73, "DZ"],
    ["Mohamed Amoura", "ES Setif", 75, "DZ"],
    ["Houssem Ghacha", "ES Setif", 72, "DZ"],
    ["Billel Benhammouda", "USM Alger", 72, "DZ"]
  ]),
  "south-african-premiership": squad("South African Premiership", "za", 8, [
    ["Ronwen Williams", "Mamelodi Sundowns", 77, "ZA"],
    ["Khuliso Mudau", "Mamelodi Sundowns", 74, "ZA"],
    ["Mothobi Mvala", "Mamelodi Sundowns", 74, "ZA"],
    ["Grant Kekana", "Mamelodi Sundowns", 74, "ZA"],
    ["Aubrey Modiba", "Mamelodi Sundowns", 74, "ZA"],
    ["Teboho Mokoena", "Mamelodi Sundowns", 76, "ZA"],
    ["Sphelele Mkhulise", "Mamelodi Sundowns", 74, "ZA"],
    ["Themba Zwane", "Mamelodi Sundowns", 77, "ZA"],
    ["Peter Shalulile", "Mamelodi Sundowns", 77, "NA"],
    ["Iqraam Rayners", "Stellenbosch", 75, "ZA"],
    ["Percy Tau", "Mamelodi Sundowns", 78, "ZA"],
    ["Itumeleng Khune", "Kaizer Chiefs", 73, "ZA"],
    ["Veli Mothwa", "AmaZulu", 72, "ZA"],
    ["Thapelo Morena", "Mamelodi Sundowns", 74, "ZA"],
    ["Siyanda Xulu", "SuperSport United", 72, "ZA"],
    ["Nkosinathi Sibisi", "Orlando Pirates", 73, "ZA"],
    ["Innocent Maela", "Orlando Pirates", 73, "ZA"],
    ["Andile Jali", "Moroka Swallows", 74, "ZA"],
    ["Monnapule Saleng", "Orlando Pirates", 75, "ZA"],
    ["Relebohile Mofokeng", "Orlando Pirates", 74, "ZA"],
    ["Patrick Maswanganyi", "Orlando Pirates", 75, "ZA"],
    ["Zakhele Lepasa", "Orlando Pirates", 74, "ZA"],
    ["Ashley Du Preez", "Kaizer Chiefs", 73, "ZA"],
    ["Evidence Makgopa", "Orlando Pirates", 73, "ZA"],
    ["Lucas Ribeiro", "Mamelodi Sundowns", 75, "BR"],
    ["Gaston Sirino", "Mamelodi Sundowns", 74, "UY"]
  ]),
  "tunisian-ligue-professionnelle": squad("Tunisian Ligue Professionnelle", "tn", 8, [
    ["Moez Ben Cherifia", "Esperance de Tunis", 74, "TN"],
    ["Hamza Mathlouthi", "Esperance de Tunis", 73, "TN"],
    ["Yassine Meriah", "Esperance de Tunis", 75, "TN"],
    ["Montassar Talbi", "Esperance de Tunis", 76, "TN"],
    ["Ali Maaloul", "CS Sfaxien", 77, "TN"],
    ["Ferjani Sassi", "Esperance de Tunis", 76, "TN"],
    ["Mohamed Ali Ben Romdhane", "Esperance de Tunis", 75, "TN"],
    ["Youssef Msakni", "Esperance de Tunis", 77, "TN"],
    ["Anis Ben Slimane", "Esperance de Tunis", 75, "TN"],
    ["Taha Yassine Khenissi", "Esperance de Tunis", 74, "TN"],
    ["Hannibal Mejbri", "Esperance de Tunis", 75, "TN"],
    ["Aymen Dahmen", "CS Sfaxien", 73, "TN"],
    ["Farouk Ben Mustapha", "Club Africain", 73, "TN"],
    ["Wajdi Kechrida", "Etoile du Sahel", 73, "TN"],
    ["Bilel Ifa", "Club Africain", 72, "TN"],
    ["Dylan Bronn", "Esperance de Tunis", 75, "TN"],
    ["Mohamed Drager", "Club Africain", 73, "TN"],
    ["Ellyes Skhiri", "Esperance de Tunis", 78, "TN"],
    ["Saad Bguir", "Esperance de Tunis", 74, "TN"],
    ["Firas Chaouat", "CS Sfaxien", 73, "TN"],
    ["Hamza Rafia", "Club Africain", 74, "TN"],
    ["Seifeddine Jaziri", "Club Africain", 74, "TN"],
    ["Issam Jebali", "Etoile du Sahel", 74, "TN"],
    ["Haythem Jouini", "Esperance de Tunis", 72, "TN"],
    ["Naim Sliti", "Club Africain", 75, "TN"],
    ["Yoann Touzghar", "Club Africain", 72, "TN"]
  ]),
  "cypriot-first-division": squad("Cypriot First Division", "cy", 8, [
    ["Vid Belec", "APOEL", 74, "SI"],
    ["Issam Chebake", "APOEL", 72, "MA"],
    ["Radosav Petrovic", "APOEL", 73, "RS"],
    ["Valentin Roberge", "Apollon Limassol", 73, "FR"],
    ["Adam Matthews", "Omonia", 72, "WAL"],
    ["Marius Lundemo", "APOEL", 72, "NO"],
    ["Chambos Kyriakou", "Apollon Limassol", 72, "CY"],
    ["Marquinhos", "APOEL", 74, "BR"],
    ["Bruno Felipe", "Omonia", 73, "BR"],
    ["Willy Semedo", "Omonia", 74, "CV"],
    ["Jairo", "Pafos", 74, "BR"],
    ["Fabiano", "Omonia", 73, "BR"],
    ["Joel Mall", "Apollon Limassol", 72, "CY"],
    ["Anderson Correia", "Anorthosis", 71, "CY"],
    ["Hector Yuste", "Omonia", 72, "ES"],
    ["Nemanja Miletic", "Omonia", 72, "RS"],
    ["Nicholas Ioannou", "APOEL", 72, "CY"],
    ["Costakis Artymatas", "Anorthosis", 72, "CY"],
    ["Mateo Susic", "APOEL", 72, "BA"],
    ["Roman Bezjak", "APOEL", 72, "SI"],
    ["Loizos Loizou", "Omonia", 73, "CY"],
    ["Pieros Sotiriou", "APOEL", 74, "CY"],
    ["Andronikos Kakoullis", "Omonia", 72, "CY"],
    ["Rafael Lopes", "AEK Larnaca", 72, "PT"],
    ["Charalampos Charalampous", "Omonia", 72, "CY"],
    ["Ivan Trickovski", "AEK Larnaca", 73, "MK"]
  ]),
  "a-league-men": squad("A-League Men", "au", 8, [
    ["Mathew Ryan", "Central Coast Mariners", 77, "AU"],
    ["Jason Geria", "Melbourne Victory", 72, "AU"],
    ["Trent Sainsbury", "Central Coast Mariners", 74, "AU"],
    ["Thomas Deng", "Melbourne Victory", 72, "AU"],
    ["Aziz Behich", "Melbourne City", 74, "AU"],
    ["Luke Brattan", "Macarthur FC", 73, "AU"],
    ["Josh Nisbet", "Central Coast Mariners", 72, "AU"],
    ["Daniel Arzani", "Melbourne Victory", 73, "AU"],
    ["Craig Goodwin", "Adelaide United", 75, "AU"],
    ["Jamie Maclaren", "Melbourne City", 75, "AU"],
    ["Bruno Fornaroli", "Melbourne Victory", 75, "AU"],
    ["Joe Gauci", "Adelaide United", 72, "AU"],
    ["Andrew Redmayne", "Sydney FC", 72, "AU"],
    ["Rhyan Grant", "Sydney FC", 72, "AU"],
    ["Alex Wilkinson", "Sydney FC", 72, "AU"],
    ["Kye Rowles", "Central Coast Mariners", 73, "AU"],
    ["Joel King", "Sydney FC", 71, "AU"],
    ["Aiden O'Neill", "Melbourne City", 73, "AU"],
    ["Anthony Caceres", "Sydney FC", 72, "AU"],
    ["Ulises Davila", "Macarthur FC", 74, "MX"],
    ["Marco Tilio", "Melbourne City", 73, "AU"],
    ["Adam Taggart", "Perth Glory", 74, "AU"],
    ["Mitchell Duke", "Western Sydney Wanderers", 74, "AU"],
    ["Nestory Irankunda", "Adelaide United", 73, "AU"],
    ["Ben Halloran", "Adelaide United", 72, "AU"],
    ["Angel Torres", "Central Coast Mariners", 73, "CO"]
  ]),
  "qatar-stars-league": squad("Qatar Stars League", "qa", 8, [
    ["Meshaal Barsham", "Al Sadd", 74, "QA"],
    ["Pedro Miguel", "Al Sadd", 74, "QA"],
    ["Boualem Khoukhi", "Al Sadd", 75, "QA"],
    ["Lucas Mendes", "Al Wakrah", 74, "QA"],
    ["Abdelkarim Hassan", "Al Sadd", 75, "QA"],
    ["Assim Madibo", "Al Duhail", 73, "QA"],
    ["Marco Verratti", "Al Arabi", 86, "IT"],
    ["Akram Afif", "Al Sadd", 80, "QA"],
    ["Yacine Brahimi", "Al Gharafa", 80, "DZ"],
    ["Michael Olunga", "Al Duhail", 79, "KE"],
    ["Almoez Ali", "Al Duhail", 78, "QA"],
    ["Saad Al Sheeb", "Al Sadd", 73, "QA"],
    ["Salah Zakaria", "Al Duhail", 72, "QA"],
    ["Tarek Salman", "Al Sadd", 73, "QA"],
    ["Bassam Al Rawi", "Al Duhail", 74, "QA"],
    ["Homam Ahmed", "Al Gharafa", 73, "QA"],
    ["Sultan Al Brake", "Al Duhail", 72, "QA"],
    ["Rodrigo Tabata", "Al Rayyan", 75, "QA"],
    ["Abdelaziz Hatem", "Al Rayyan", 74, "QA"],
    ["Santi Cazorla", "Al Sadd", 79, "ES"],
    ["Rafinha", "Al Arabi", 76, "BR"],
    ["Ibrahim Afellay", "Al Sadd", 74, "NL"],
    ["Baghdad Bounedjah", "Al Shamal", 78, "DZ"],
    ["Yohan Boli", "Al Gharafa", 75, "CI"],
    ["Sofiane Hanni", "Al Ahli", 75, "DZ"],
    ["Gabriel Pereira", "Al Rayyan", 76, "BR"]
  ]),
  "primera-costa-rica": squad("Primera Division Costa Rica", "cr", 8, [
    ["Keylor Navas", "Saprissa", 80, "CR"],
    ["Keysher Fuller", "Herediano", 73, "CR"],
    ["Kendall Waston", "Saprissa", 74, "CR"],
    ["Francisco Calvo", "Saprissa", 75, "CR"],
    ["Bryan Oviedo", "Saprissa", 74, "CR"],
    ["Celso Borges", "Alajuelense", 75, "CR"],
    ["Yeltsin Tejeda", "Herediano", 73, "CR"],
    ["Joel Campbell", "Alajuelense", 76, "CR"],
    ["Gerson Torres", "Herediano", 73, "CR"],
    ["Marcel Hernandez", "Cartagines", 74, "CU"],
    ["Manfred Ugalde", "Saprissa", 75, "CR"],
    ["Leonel Moreira", "Alajuelense", 72, "CR"],
    ["Esteban Alvarado", "Herediano", 72, "CR"],
    ["Carlos Martinez", "Alajuelense", 72, "CR"],
    ["Juan Pablo Vargas", "Millonarios", 74, "CR"],
    ["Oscar Duarte", "Saprissa", 74, "CR"],
    ["Ian Lawrence", "Alajuelense", 71, "CR"],
    ["Orlando Galo", "Herediano", 72, "CR"],
    ["Youstin Salas", "Saprissa", 72, "CR"],
    ["Ariel Rodriguez", "Saprissa", 73, "CR"],
    ["Alvaro Zamora", "Saprissa", 73, "CR"],
    ["Johan Venegas", "Alajuelense", 73, "CR"],
    ["Anthony Contreras", "Herediano", 73, "CR"],
    ["Jonathan Moya", "Alajuelense", 72, "CR"],
    ["Randall Leal", "Saprissa", 73, "CR"],
    ["Warren Madrigal", "Saprissa", 73, "CR"]
  ]),
  "chinese-super-league": squad("Chinese Super League", "cn", 8, [
    ["Yan Junling", "Shanghai Port", 75, "CN"],
    ["Wang Shenchao", "Shanghai Port", 73, "CN"],
    ["Browning", "Shanghai Port", 74, "CN"],
    ["Zhu Chenjie", "Shanghai Shenhua", 73, "CN"],
    ["Li Lei", "Beijing Guoan", 72, "CN"],
    ["Oscar", "Shanghai Port", 82, "BR"],
    ["Wu Xi", "Shanghai Shenhua", 74, "CN"],
    ["Cryzan", "Shandong Taishan", 77, "BR"],
    ["Wu Lei", "Shanghai Port", 78, "CN"],
    ["Felipe", "Chengdu Rongcheng", 76, "BR"],
    ["Matias Vargas", "Shanghai Port", 77, "AR"],
    ["Wang Dalei", "Shandong Taishan", 73, "CN"],
    ["Bao Yaxiong", "Shanghai Shenhua", 72, "CN"],
    ["Gao Zhunyi", "Shandong Taishan", 72, "CN"],
    ["Jiang Guangtai", "Shanghai Port", 73, "CN"],
    ["Tyias Browning", "Shanghai Port", 74, "CN"],
    ["Liu Yang", "Shandong Taishan", 72, "CN"],
    ["Romulo", "Chengdu Rongcheng", 76, "BR"],
    ["Moises", "Shandong Taishan", 77, "BR"],
    ["Nico Yennaris", "Beijing Guoan", 73, "CN"],
    ["Conrado", "Meizhou Hakka", 74, "BR"],
    ["Leonardo", "Zhejiang", 77, "BR"],
    ["Elkeson", "Chengdu Rongcheng", 75, "CN"],
    ["Alan Carvalho", "Qingdao West Coast", 74, "CN"],
    ["Wei Shihao", "Chengdu Rongcheng", 74, "CN"],
    ["Xie Pengfei", "Shanghai Shenhua", 73, "CN"]
  ])
};

function squad(label, prefix, captainIndex, rows, formation = "4-3-3") {
  const players = rows.map(([name, club, rating, nationalityCode], index) => {
    const [shirtNumber, position, role] = squadSlots[index];
    const nationality = nationalityFor(nationalityCode, name);
    return {
      id: `${prefix}-${slug(name)}`,
      name,
      shirtNumber,
      position,
      role,
      rating,
      club,
      nationality,
      isStarter: index < starterSlots.length
    };
  });

  return {
    formation,
    sourceNote: `Plantilla real semilla basada en jugadores destacados y planteles de clubes de ${label} 2025-26.`,
    captainId: players[captainIndex]?.id ?? players[0].id,
    players
  };
}

function nationalityFor(code, playerName) {
  if (!code) {
    throw new Error(`Missing nationality code for ${playerName}`);
  }

  const [country, emoji] = countries[code] ?? [];
  if (!country || !emoji) {
    throw new Error(`Unknown nationality code ${code} for ${playerName}`);
  }

  return { code, country, emoji, isExplicit: true };
}

function slug(value) {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}
